"use client";
import { broadcastOfflineCommerceChange, openOfflineCommerceDb, requestPromise, transactionDone } from "./commerce-db";
import type { CommerceStoredCart, CommerceStoredHeldSale, CommerceStoredSocialDraft } from "./commerce-types";
export function createCommerceTransactionId(): string { return typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `commerce-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
const cartKey=(shopId:number)=>`v2:cart:${shopId}`; const socialKey=(employeeId:number)=>`v2:social:${employeeId}`;
export async function saveV2PosCart<T>(shopId:number,payload:T){const db=await openOfflineCommerceDb();const tx=db.transaction("carts","readwrite");tx.objectStore("carts").put({key:cartKey(shopId),shopId,source:"v2",payload,updatedAt:new Date().toISOString()} satisfies CommerceStoredCart);await transactionDone(tx);}
export async function loadV2PosCart<T>(shopId:number):Promise<T|null>{const db=await openOfflineCommerceDb();const tx=db.transaction("carts","readonly");const done=transactionDone(tx);const row=await requestPromise(tx.objectStore("carts").get(cartKey(shopId))) as CommerceStoredCart|undefined;await done;return row?.source==="v2"?row.payload as T:null;}
export async function clearV2PosCart(shopId:number){const db=await openOfflineCommerceDb();const tx=db.transaction("carts","readwrite");tx.objectStore("carts").delete(cartKey(shopId));await transactionDone(tx);}
export async function holdV2PosSale<T>(shopId:number,payload:T){const sale={id:createCommerceTransactionId(),shopId,source:"v2" as const,payload,createdAt:new Date().toISOString()};const db=await openOfflineCommerceDb();const tx=db.transaction("held_sales","readwrite");tx.objectStore("held_sales").put(sale);await transactionDone(tx);broadcastOfflineCommerceChange({type:"held_sale_changed",shopId});return sale;}
export async function listV2HeldSales<T>(shopId:number){const db=await openOfflineCommerceDb();const tx=db.transaction("held_sales","readonly");const done=transactionDone(tx);const rows=await requestPromise(tx.objectStore("held_sales").index("shopId").getAll(IDBKeyRange.only(shopId))) as CommerceStoredHeldSale[];await done;return rows.filter(r=>r.source==="v2").map(r=>({...r,payload:r.payload as T}));}
export async function deleteV2HeldSale(id:string){const db=await openOfflineCommerceDb();const tx=db.transaction("held_sales","readwrite");tx.objectStore("held_sales").delete(id);await transactionDone(tx);broadcastOfflineCommerceChange({type:"held_sale_changed"});}
export async function saveV2SocialDraft<T>(employeeId:number,shopId:number|null,payload:T){const db=await openOfflineCommerceDb();const tx=db.transaction("social_drafts","readwrite");tx.objectStore("social_drafts").put({key:socialKey(employeeId),shopId,employeeId,source:"v2",payload,updatedAt:new Date().toISOString()} satisfies CommerceStoredSocialDraft);await transactionDone(tx);}
export async function loadV2SocialDraft<T>(employeeId:number):Promise<T|null>{const db=await openOfflineCommerceDb();const tx=db.transaction("social_drafts","readonly");const done=transactionDone(tx);const row=await requestPromise(tx.objectStore("social_drafts").get(socialKey(employeeId))) as CommerceStoredSocialDraft|undefined;await done;return row?.source==="v2"?row.payload as T:null;}
export async function clearV2SocialDraft(employeeId:number){const db=await openOfflineCommerceDb();const tx=db.transaction("social_drafts","readwrite");tx.objectStore("social_drafts").delete(socialKey(employeeId));await transactionDone(tx);}
