import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";
export const metadata: Metadata = { title: "Returns & exchange | HajjMart" };
export default function ReturnsPage(){return <PolicyPage eyebrow={{bn:"গ্রাহক সেবা",en:"Customer care"}} title={{bn:"রিটার্ন, রিফান্ড ও এক্সচেঞ্জ",en:"Returns, refunds & exchange"}} intro={{bn:"আমরা চাই প্রতিটি HajjMart অর্ডার সঠিকভাবে পৌঁছাক এবং সত্যিই কাজে লাগুক। এখানে সাধারণ প্রক্রিয়া দেওয়া আছে; চূড়ান্ত যোগ্যতা পণ্যের অবস্থা ও অর্ডারের বিস্তারিত তথ্যের ওপর নির্ভর করে।",en:"We want every HajjMart order to arrive correctly and be genuinely useful. This page explains the general process; final eligibility depends on the product condition and order details."}} sections={[
{title:{bn:"সহায়তার অনুরোধ",en:"Requesting support"},paragraphs:[{bn:"পার্সেল পাওয়ার পর দ্রুত HajjMart-এর সাথে যোগাযোগ করুন এবং অর্ডার রেফারেন্স, পণ্যের নাম ও অনুরোধের কারণ জানান।",en:"Contact HajjMart promptly after receiving the parcel and share the order reference, item name and the reason for the request."}],bullets:[{bn:"মূল প্যাকেজিং, লেবেল ও আনুষঙ্গিক জিনিস সংরক্ষণ করুন।",en:"Keep the original packaging, labels and accessories."},{bn:"যে পণ্য ফেরত দিতে চান তা ব্যবহার, ধোয়া বা পরিবর্তন করবেন না।",en:"Do not use, wash or alter an item you intend to return."},{bn:"ভুল বা ক্ষতিগ্রস্ত পণ্যের ক্ষেত্রে পরিষ্কার ছবি দিন।",en:"Provide clear photos when the product is incorrect or damaged."}]},
{title:{bn:"যোগ্য এক্সচেঞ্জ",en:"Eligible exchanges"},paragraphs:[{bn:"স্টক থাকলে অব্যবহৃত পণ্য সাইজ, ভ্যারিয়েশন বা অন্য পণ্যে বদলের যোগ্য হতে পারে। স্বাস্থ্যবিধি-সংবেদনশীল বা খোলা ব্যক্তিগত যত্নের পণ্য যাচাইকৃত ত্রুটি বা প্রেরণ ভুল ছাড়া যোগ্য নাও হতে পারে।",en:"Unused products may be eligible for size, variation or product exchange when stock is available. Hygiene-sensitive or opened personal-care items may not be eligible unless there is a verified defect or dispatch error."}]},
{title:{bn:"রিফান্ড",en:"Refunds"},paragraphs:[{bn:"অনুমোদিত রিফান্ড ডিসকাউন্ট ও কুপন বণ্টনের পর পরিশোধিত নেট মূল্যের ভিত্তিতে হিসাব করা হয়। রিটার্নের কারণ ও প্রযোজ্য নীতির ওপর ভিত্তি করে ডেলিভারি বা রিটার্ন খরচ সমন্বয় হতে পারে।",en:"Approved refunds are calculated from the net amount paid after discounts and coupon allocation. Delivery or return costs may be adjusted according to the reason for the return and the applicable policy."}]},
{title:{bn:"প্রক্রিয়াকরণ",en:"Processing"},paragraphs:[{bn:"অনুরোধ পর্যালোচনা করে টিম রিটার্নের পদ্ধতি ও আনুমানিক সময় জানাবে। HajjMart-এর রিটার্ন নির্দেশনা পাওয়ার আগে কোনো পার্সেল পাঠাবেন না।",en:"The team will explain the return route and expected processing time after reviewing the request. Do not send a parcel without first receiving return instructions from HajjMart."}]}
]}/>}
