import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";
export const metadata: Metadata = { title: "Privacy policy | HajjMart" };
export default function PrivacyPage(){return <PolicyPage eyebrow={{bn:"আপনার গোপনীয়তা",en:"Your privacy"}} title={{bn:"গোপনীয়তা নীতি",en:"Privacy policy"}} intro={{bn:"হজমার্ট গ্রাহকের তথ্য শুধু স্টোর পরিচালনা, অর্ডার প্রক্রিয়া এবং সেবা উন্নত করার জন্য ব্যবহার করে।",en:"HajjMart uses customer information only to operate the store, process orders and improve service."}} sections={[
{title:{bn:"আমরা যে তথ্য সংগ্রহ করি",en:"Information we collect"},paragraphs:[{bn:"আমরা নাম, ইমেইল ঠিকানা, মোবাইল নম্বর, ডেলিভারি ঠিকানা, অ্যাকাউন্টের তথ্য, অর্ডারের তথ্য এবং আমাদের টিমকে পাঠানো বার্তা সংগ্রহ করতে পারি।",en:"We may collect names, email addresses, mobile numbers, delivery addresses, account details, order information and messages you send to the team."}]},
{title:{bn:"তথ্য কীভাবে ব্যবহার করা হয়",en:"How information is used"},paragraphs:[{bn:"অর্ডার পূরণ, ডেলিভারি সমন্বয়, অ্যাকাউন্ট সুবিধা, সহায়তার অনুরোধের উত্তর, জালিয়াতি প্রতিরোধ এবং আইনি বা হিসাব সংক্রান্ত প্রয়োজন পূরণে তথ্য ব্যবহার করা হয়।",en:"Information is used to fulfil orders, coordinate delivery, provide account features, respond to support requests, prevent fraud and meet legal or accounting requirements."}]},
{title:{bn:"পেমেন্ট",en:"Payments"},paragraphs:[{bn:"অনলাইন পেমেন্ট কনফিগার করা পেমেন্ট প্রদানকারীদের মাধ্যমে পরিচালিত হয়। হজমার্ট স্টোরফ্রন্টে পূর্ণ কার্ড তথ্য সংরক্ষণ করার প্রয়োজন নেই।",en:"Online payments are handled through configured payment providers. HajjMart does not need to store full card credentials in the storefront."}]},
{title:{bn:"আপনার তথ্যের পছন্দ",en:"Data choices"},paragraphs:[{bn:"অ্যাকাউন্টের তথ্য সংশোধন চাইতে বা আপনার তথ্য কীভাবে ব্যবহৃত হয় সে বিষয়ে প্রশ্ন করতে হজমার্টের সাথে যোগাযোগ করতে পারেন।",en:"You may request correction of account information or ask questions about how your information is handled by contacting HajjMart."}]}
]}/>}
