"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { useStore } from "@/context/store-context";
import { adminRequest, pageRows } from "@/lib/admin-api";
import { demoEmployees, demoRoles } from "@/lib/admin-demo";
import type { AdminRole, AdminUser, Paginated } from "@/lib/admin-types";
import { AdminButton, AdminIcon, Drawer, Field, FormGrid, PageHeader, Panel, SearchField, StatusBadge, TableShell } from "@/components/admin/admin-ui";

export default function EmployeesPage(){
 const {token,stores,demoMode}=useAdmin(); const {notify}=useStore();
 const [rows,setRows]=useState<AdminUser[]>([]); const [roles,setRoles]=useState<AdminRole[]>([]); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<AdminUser|null>(null); const [createOpen,setCreateOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(demoMode){setRows(demoEmployees);setRoles(demoRoles);setError(null);return}if(!token)return;const controller=new AbortController();setError(null);void Promise.all([adminRequest<Paginated<AdminUser>|AdminUser[]>("/employees?per_page=100",{token,signal:controller.signal}),adminRequest<AdminRole[]>("/roles",{token,signal:controller.signal})]).then(([employees,nextRoles])=>{if(controller.signal.aborted)return;setRows(pageRows(employees));setRoles(nextRoles)}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Employees could not be loaded.")});return()=>controller.abort()},[token,demoMode]);
 const filtered=useMemo(()=>rows.filter(e=>`${e.name} ${e.email} ${e.employee_code} ${e.designation}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError(null);try{const role=roles.find(r=>r.id===Number(d.get("role_id")))||roles[0];const shop=stores.find(s=>s.id===Number(d.get("shop_id")))||stores[0];const payload={name:String(d.get("name")),employee_code:String(d.get("employee_code")),email:String(d.get("email")),phone:String(d.get("phone")||""),designation:String(d.get("designation")||""),employment_type:String(d.get("employment_type")||"full_time"),shop_id:shop?.id||null,role_ids:role?[role.id]:[],password:String(d.get("password")),is_active:true};let employee:AdminUser;if(demoMode||!token){employee={id:Date.now(),...payload,shop,roles:role?[role]:[],role_names:role?[role.name]:[],permission_names:role?.permissions.map(p=>p.name)||[],role:"employee"};}else employee=await adminRequest<AdminUser>("/employees",{method:"POST",token,body:payload});setRows(c=>[employee,...c]);setCreateOpen(false);notify("Employee created and role access assigned.");}catch(reason){setError(reason instanceof Error?reason.message:"Employee could not be created.");}finally{setBusy(false)}}
 async function toggleEmployee(){if(!selected)return;setBusy(true);setError(null);try{const active=!selected.is_active;let updated:AdminUser={...selected,is_active:active};if(!demoMode&&token)updated=await adminRequest<AdminUser>(`/employees/${selected.id}/toggle`,{method:"PUT",token,body:{is_active:active}});setRows(c=>c.map(e=>e.id===updated.id?updated:e));setSelected(updated);notify(active?"Employee access restored.":"Employee access disabled. Historical activity remains intact.");}catch(reason){setError(reason instanceof Error?reason.message:"Employee status could not be updated.");}finally{setBusy(false)}}
 return <><PageHeader title="Employees" description="Create employee accounts, assign a home store and attach one or more roles. Disabling an employee preserves all historical activity." actions={<AdminButton icon="plus" onClick={()=>{setError(null);setCreateOpen(true)}}>Add employee</AdminButton>}/>{error&&<p className="admin-form-error">{error}</p>}
 <div className="admin-inline-metrics"><div><span>Total employees</span><strong>{rows.length}</strong></div><div><span>Active accounts</span><strong>{rows.filter(e=>e.is_active).length}</strong></div><div><span>Store managers</span><strong>{rows.filter(e=>e.role_names?.includes("Store Manager")).length}</strong></div><div><span>Disabled</span><strong>{rows.filter(e=>!e.is_active).length}</strong></div></div>
 <Panel><div className="admin-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Name, email, code or designation…"/><AdminButton variant="secondary" icon="download" onClick={()=>notify("Employee directory export prepared.")}>Export</AdminButton></div><TableShell><thead><tr><th>Employee</th><th>Role</th><th>Store</th><th>Employment</th><th>Access status</th><th></th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} onClick={()=>setSelected(e)} className="admin-clickable-row"><td><div className="admin-employee-cell"><span>{e.name.split(" ").slice(0,2).map(p=>p[0]).join("")}</span><div><strong>{e.name}</strong><small>{e.employee_code} · {e.email}<br/>{e.phone}</small></div></div></td><td><strong>{e.role_names?.join(", ")||e.role}</strong><small>{e.designation}</small></td><td>{e.shop?.name||"All stores"}</td><td>{(e.employment_type||"full_time").replaceAll("_"," ")}</td><td><StatusBadge value={e.is_active?"active":"disabled"}/></td><td className="align-right"><button className="admin-icon-button"><AdminIcon name="chevron"/></button></td></tr>)}</tbody></TableShell></Panel>
 <Drawer open={createOpen} onClose={()=>!busy&&setCreateOpen(false)} title="Add employee" subtitle="Create the account, place it in a store and apply role-based page access."><form className="admin-stack" onSubmit={create}><FormGrid><Field label="Full name" required><input name="name" required/></Field><Field label="Employee code"><input name="employee_code" placeholder="HM-021"/></Field><Field label="Work email" required><input name="email" type="email" required/></Field><Field label="Mobile number"><input name="phone"/></Field><Field label="Designation"><input name="designation"/></Field><Field label="Employment type"><select name="employment_type"><option value="full_time">Full-time</option><option value="part_time">Part-time</option><option value="contract">Contract</option><option value="intern">Intern</option></select></Field><Field label="Home store"><select name="shop_id">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Role"><select name="role_id">{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field></FormGrid><Field label="Temporary password" hint="Ask the employee to change it on first login."><input name="password" type="password" defaultValue="ChangeMe123!" minLength={8} required/></Field>{error&&<p className="admin-form-error">{error}</p>}<AdminButton icon="check" disabled={busy}>{busy?"Creating…":"Create employee"}</AdminButton></form></Drawer>
 <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.name||"Employee"} subtitle={`${selected?.employee_code||""} · ${selected?.designation||""}`}>{selected&&<div className="admin-stack"><div className="admin-employee-profile"><span>{selected.name.split(" ").slice(0,2).map(p=>p[0]).join("")}</span><div><h3>{selected.name}</h3><p>{selected.email}<br/>{selected.phone}</p></div><StatusBadge value={selected.is_active?"active":"disabled"}/></div><Panel title="Assignment"><div className="admin-detail-grid"><div><span>Store</span><strong>{selected.shop?.name||"All stores"}</strong></div><div><span>Role</span><strong>{selected.role_names?.join(", ")}</strong></div><div><span>Designation</span><strong>{selected.designation}</strong></div><div><span>Permissions</span><strong>{selected.permission_names?.length||0}</strong><small>resolved from role assignment</small></div></div></Panel><Panel title="Page access"><div className="admin-permission-chips">{(selected.permission_names||[]).slice(0,18).map(p=><span key={p}>{p}</span>)}</div></Panel>{error&&<p className="admin-form-error">{error}</p>}<div className="admin-action-strip"><AdminButton icon="edit" onClick={()=>notify("Use the employee API to update profile, store and role assignments.")}>Edit employee</AdminButton><AdminButton variant="secondary" icon="roles" onClick={()=>notify("Role definitions are managed from Roles & Access.")}>Manage roles</AdminButton><AdminButton variant={selected.is_active?"danger":"primary"} disabled={busy} onClick={toggleEmployee}>{busy?"Updating…":selected.is_active?"Disable access":"Restore access"}</AdminButton></div></div>}</Drawer></>;
}
