"use client";
import { createContext,useCallback,useContext,useEffect,useMemo,useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { bootstrapAndInstallOfflineCommerce } from "@/lib/offline/commerce-session";
import { subscribeOfflineCommerceChanges } from "@/lib/offline/commerce-db";
import { readOfflineCommerceState,type OfflineCommerceState } from "@/lib/offline/commerce-readiness";
const initial={} as OfflineCommerceState;
const C=createContext<{state:OfflineCommerceState;refresh:()=>Promise<OfflineCommerceState>;prepareForCommit:(shopId:number)=>Promise<OfflineCommerceState>}|null>(null);
export function OfflineCommerceProvider({children}:{children:React.ReactNode}){const{token,demoMode}=useAdmin();const[state,setState]=useState<OfflineCommerceState>(initial);const refresh=useCallback(async()=>{const n=await readOfflineCommerceState();setState(n);return n;},[]);useEffect(()=>{if(demoMode)return;void refresh();const off=subscribeOfflineCommerceChanges(()=>void refresh());const h=()=>void refresh();window.addEventListener("online",h);window.addEventListener("offline",h);window.addEventListener("hajjmart-commerce-device-change",h);return()=>{off();window.removeEventListener("online",h);window.removeEventListener("offline",h);window.removeEventListener("hajjmart-commerce-device-change",h);};},[demoMode,refresh]);const prepareForCommit=useCallback(async(shopId:number)=>{let current=await refresh();if(!current.registeredDevice||current.boundShopId!==shopId||!current.storageHealthy||current.legacyPendingCount||current.operationalState==="recovery_required")return current;const stale=!current.session||Boolean(current.session?.reconciledAt)||current.blockReasonCode==="offline_snapshot_too_old";const revision=current.session&&current.serverInventoryRevision!=null&&current.snapshotInventoryRevision!=null&&current.serverInventoryRevision!==current.snapshotInventoryRevision;if(token&&current.backendReachable&&current.unsyncedV2EventCount===0&&(stale||revision)){try{await bootstrapAndInstallOfflineCommerce(token,{refreshSnapshot:Boolean(current.session),unsyncedEventCount:0,lastKnownSessionId:current.currentSessionId,lastLocalSequence:current.session?.reconciledAt ? 0 : current.lastLocalSequence,clientSchemaVersion:"1"});current=await refresh();}catch{current=await refresh();}}return current;},[refresh,token]);return <C.Provider value={useMemo(()=>({state,refresh,prepareForCommit}),[state,refresh,prepareForCommit])}>{children}</C.Provider>;}export function useOfflineCommerce(){const v=useContext(C);if(!v)throw new Error("OfflineCommerceProvider missing");return v;}
