import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";
export const metadata: Metadata = { title: "Terms & conditions | HajjMart" };
export default function TermsPage(){return <PolicyPage eyebrow={{bn:"স্টোরের শর্ত",en:"Store terms"}} title={{bn:"শর্তাবলি",en:"Terms & conditions"}} intro={{bn:"হজমার্ট ওয়েবসাইট ব্যবহার বা অর্ডার করার মাধ্যমে আপনি এই সাধারণ স্টোর শর্তাবলিতে সম্মত হন।",en:"By using the HajjMart website or placing an order, you agree to these general store terms."}} sections={[
{title:{bn:"পণ্যের তথ্য",en:"Product information"},paragraphs:[{bn:"আমরা সঠিক নাম, ছবি, মূল্য ও প্রাপ্যতা দেখানোর চেষ্টা করি। রঙ বা প্যাকেজিংয়ে সামান্য পার্থক্য হতে পারে এবং অর্ডার নিশ্চিত হওয়ার আগে স্টক পরিবর্তিত হতে পারে।",en:"We aim to present accurate names, images, prices and availability. Minor colour or packaging differences may occur, and stock can change before an order is confirmed."}]},
{title:{bn:"অর্ডার ও মূল্য",en:"Orders and pricing"},paragraphs:[{bn:"অর্ডার যাচাই ও গ্রহণযোগ্যতার ওপর নির্ভরশীল। পাঠানোর আগে ভ্যারিয়েশন, ঠিকানা, পেমেন্ট বা প্রাপ্যতা নিয়ে পরিষ্কার করতে হজমার্ট আপনার সাথে যোগাযোগ করতে পারে।",en:"An order is subject to verification and acceptance. HajjMart may contact you to clarify a variation, address, payment or availability issue before dispatch."}]},
{title:{bn:"ডেলিভারি",en:"Delivery"},paragraphs:[{bn:"ডেলিভারির আনুমানিক সময় নিশ্চয়তা নয়; স্থান, কুরিয়ার কার্যক্রম, আবহাওয়া, সরকারি ছুটি ও হজ মৌসুমের চাপের কারণে পরিবর্তিত হতে পারে।",en:"Delivery estimates are not guarantees and can be affected by location, courier operations, weather, public holidays and Hajj-season demand."}]},
{title:{bn:"দায়িত্বশীল ব্যবহার",en:"Responsible use"},paragraphs:[{bn:"ওয়েবসাইটের অপব্যবহার, অননুমোদিত প্রবেশের চেষ্টা বা মিথ্যা তথ্য দেওয়া যাবে না। পণ্য ও নির্দেশনামূলক কনটেন্ট ব্যবহারিক কেনাকাটার সহায়তার জন্য; এটি যোগ্য ধর্মীয়, চিকিৎসা বা আইনি পরামর্শের বিকল্প নয়।",en:"Do not misuse the website, attempt unauthorised access or provide false information. Product and guidance content is for practical shopping support and does not replace qualified religious, medical or legal advice."}]}
]}/>}
