<?php

namespace Database\Seeders;

use App\Models\BusinessTransaction;
use App\Models\Coupon;
use App\Models\CouponApplication;
use App\Models\DailySalesSummary;
use App\Models\Inventory;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\OrderList;
use App\Models\OrderStatusHistory;
use App\Models\Payment;
use App\Models\Product;
use App\Models\ProductBatch;
use App\Models\ReturnRequest;
use App\Models\ReturnRequestItem;
use App\Models\ReturnStatusHistory;
use App\Models\Role;
use App\Models\Shop;
use App\Models\StockMovement;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class HajjMartDemoOperationsSeeder extends Seeder
{
    private array $firstNames = ['Arafat', 'Nusrat', 'Sakib', 'Maliha', 'Tanvir', 'Farzana', 'Mahmud', 'Rukaiya', 'Hasan', 'Jannat', 'Rafi', 'Sumaiya', 'Nayeem', 'Tasnim', 'Imran'];
    private array $lastNames = ['Rahman', 'Ahmed', 'Islam', 'Hossain', 'Khan', 'Akter', 'Siddique', 'Karim', 'Chowdhury', 'Hasan'];
    private array $districts = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Cumilla', 'Mymensingh', 'Barishal', 'Rangpur', 'Gazipur'];

    public function run(): void
    {
        DB::transaction(function (): void {
            $shop = Shop::defaultStore();
            $admin = User::where('email', 'admin@hajjmart.local')->firstOrFail();
            $orderList = OrderList::firstOrCreate(['shop_id' => $shop->id]);

            $this->resetSeededOperations();
            $employees = $this->seedEmployees($shop, $admin);
            $customers = $this->seedCustomers();
            $products = Product::with(['productVariants', 'productImages', 'primaryCategory'])->where('is_active', true)->get();
            if ($products->isEmpty()) {
                throw new \RuntimeException('No products are available. Run HajjMartProductSeeder before HajjMartDemoOperationsSeeder.');
            }

            $orders = $this->seedOrders($products, $customers, $orderList, $shop, $admin, $employees);
            $this->seedReturns($orders, $products, $shop, $admin);
            $this->seedTransactions($shop, $admin, $employees);
            $this->resetEverySellableSkuToFifty($products, $shop, $admin);
            $this->seedDailySummaries();
        });

        $this->command?->info('Seeded 300 orders, 20 return/exchange/refunds, 15 employees, 3 roles, transactions, and direct batches with 50 units per sellable SKU.');
    }

    private function resetSeededOperations(): void
    {
        Order::where('source_reference', 'like', 'SEED-%')->get()->each->delete();
        BusinessTransaction::where('reference', 'like', 'SEED-%')->get()->each->delete();
        User::withTrashed()->where('email', 'like', 'employee%@hajjmart.local')->get()->each(fn (User $user) => $user->forceDelete());
        User::withTrashed()->where('email', 'like', 'demo.customer%@hajjmart.local')->get()->each(fn (User $user) => $user->forceDelete());
        StockMovement::where('reason_code', 'seed_stock_50')->delete();
        ProductBatch::where('batch_reference', 'like', 'SEED-DEMO-%')->delete();
    }

    private function seedEmployees(Shop $shop, User $admin)
    {
        $roles = Role::whereIn('slug', ['store_manager', 'sales_order_operator', 'inventory_manager'])->get()->keyBy('slug');
        if ($roles->count() !== 3) {
            throw new \RuntimeException('The three operational roles are missing. Run AdminAccessSeeder first.');
        }

        return collect(range(1, 15))->map(function (int $index) use ($shop, $admin, $roles): User {
            $roleSlug = match (true) {
                $index <= 5 => 'store_manager',
                $index <= 10 => 'sales_order_operator',
                default => 'inventory_manager',
            };
            $role = $roles[$roleSlug];
            $name = $this->firstNames[$index - 1] . ' ' . $this->lastNames[$index % count($this->lastNames)];
            $employee = User::updateOrCreate(
                ['email' => sprintf('employee%02d@hajjmart.local', $index)],
                [
                    'name' => $name,
                    'phone' => '01710' . str_pad((string) $index, 6, '0', STR_PAD_LEFT),
                    'password' => Hash::make('ChangeMe123!'),
                    'role' => 'employee',
                    'is_active' => true,
                    'employee_code' => sprintf('HM-EMP-%03d', $index),
                    'designation' => $role->name,
                    'employment_type' => $index % 5 === 0 ? 'part_time' : 'full_time',
                    'shop_id' => $shop->id,
                    'joined_at' => now()->subMonths(($index % 8) + 1)->toDateString(),
                    'created_by' => $admin->id,
                    'notes' => 'Deterministic demonstration employee generated by HajjMartDemoOperationsSeeder.',
                ]
            );
            $employee->roles()->sync([$role->id]);
            return $employee;
        });
    }

    private function seedCustomers()
    {
        return collect(range(1, 40))->map(function (int $index): User {
            return User::updateOrCreate(
                ['email' => sprintf('demo.customer%02d@hajjmart.local', $index)],
                [
                    'name' => $this->firstNames[$index % count($this->firstNames)] . ' ' . $this->lastNames[$index % count($this->lastNames)],
                    'phone' => '01820' . str_pad((string) $index, 6, '0', STR_PAD_LEFT),
                    'password' => Hash::make('Customer123!'),
                    'role' => 'customer',
                    'is_active' => true,
                ]
            );
        });
    }

    private function seedOrders($products, $customers, OrderList $orderList, Shop $shop, User $admin, $employees)
    {
        $coupon = Coupon::where('code', 'UMRAH5')->first();
        $couponUses = 0;
        $sources = ['ecommerce', 'social_commerce', 'pos'];
        $paymentMethods = ['cash', 'cod', 'bkash', 'nagad', 'card'];
        $orders = collect();

        for ($i = 1; $i <= 300; $i++) {
            $source = $sources[($i - 1) % 3];
            $dayIndex = intdiv($i - 1, 10);
            $orderedAt = now()->startOfDay()->subDays(29 - $dayIndex)->addHours(9 + ($i % 10))->addMinutes(($i * 7) % 60);
            $customer = $source === 'pos' ? null : $customers[($i - 1) % $customers->count()];
            $creator = $source === 'ecommerce' ? $admin : $employees[($i - 1) % $employees->count()];
            $district = $this->districts[($i - 1) % count($this->districts)];
            $status = $this->orderStatus($i);
            $itemCount = 1 + ($i % 3);
            $linePayloads = [];
            $subtotal = 0.0;
            $totalCogs = 0.0;

            for ($line = 0; $line < $itemCount; $line++) {
                $product = $products[($i * 3 + $line * 11) % $products->count()];
                $variant = $product->productVariants->isNotEmpty()
                    ? $product->productVariants[($i + $line) % $product->productVariants->count()]
                    : null;
                $unitPrice = (float) ($variant?->sale_price ?: $variant?->price ?: $product->sale_price ?: $product->selling_price ?: $product->regular_price ?: 100);
                $unitCost = (float) ($variant?->cost_price ?: $product->cost_price ?: round($unitPrice * 0.62, 2));
                $quantity = 1 + (($i + $line) % 2);
                $lineSubtotal = round($unitPrice * $quantity, 2);
                $subtotal += $lineSubtotal;
                $totalCogs += round($unitCost * $quantity, 2);
                $linePayloads[] = compact('product', 'variant', 'unitPrice', 'unitCost', 'quantity', 'lineSubtotal');
            }

            $applyCoupon = $coupon && $i % 12 === 0;
            $discount = $applyCoupon ? min(500, round($subtotal * 0.05, 2)) : ($i % 8 === 0 ? min(250, round($subtotal * 0.03, 2)) : 0.0);
            $shipping = $source === 'pos' ? 0.0 : 80.0;
            $grandTotal = max(0, round($subtotal - $discount + $shipping, 2));
            $paymentMethod = $source === 'pos' ? $paymentMethods[$i % 4] : $paymentMethods[1 + ($i % 4)];
            [$paymentStatus, $paidAmount] = $this->paymentState($i, $status, $grandTotal);
            $dueAmount = max(0, round($grandTotal - $paidAmount, 2));
            $customerName = $customer?->name ?? 'Walk-in Customer';
            $customerPhone = $customer?->phone ?? null;
            $snapshotAddress = [
                'name' => $customerName,
                'phone' => $customerPhone,
                'district' => $district,
                'address' => $source === 'pos' ? 'Counter sale' : "House " . (($i % 80) + 1) . ", Road " . (($i % 20) + 1) . ", {$district}",
                'country' => 'Bangladesh',
            ];

            $order = Order::create([
                'order_list_id' => $orderList->id,
                'order_id' => 'D' . str_pad((string) $i, 6, '0', STR_PAD_LEFT),
                'order_number' => 'HM-DEMO-' . str_pad((string) $i, 4, '0', STR_PAD_LEFT),
                'customer_id' => $customer?->id,
                'checkout_name' => $customerName,
                'checkout_country' => 'Bangladesh',
                'checkout_full_address' => $snapshotAddress['address'],
                'checkout_district' => $district,
                'checkout_mobile_number' => $customerPhone,
                'checkout_email' => $customer?->email,
                'shipping_full_address' => $snapshotAddress['address'],
                'shipping_district' => $district,
                'shipping_mobile_number' => $customerPhone,
                'shipping_email' => $customer?->email,
                'status' => $status,
                'order_status' => $status,
                'payment_status' => $paymentStatus,
                'payment_method' => $paymentMethod,
                'payment_channel' => $paymentMethod,
                'terms_accepted' => true,
                'source_channel' => $source,
                'subtotal' => $subtotal,
                'net_subtotal' => $subtotal - $discount,
                'tax_total' => 0,
                'shipping_total' => $shipping,
                'delivery_charge' => $shipping,
                'discount_total' => $discount,
                'item_discount_total' => $discount,
                'shipping_discount_total' => 0,
                'coupon_code' => $applyCoupon ? $coupon->code : null,
                'coupon_codes' => $applyCoupon ? [$coupon->code] : [],
                'promotion_snapshot' => $applyCoupon ? [['code' => $coupon->code, 'discount' => $discount]] : [],
                'grand_total' => $grandTotal,
                'total_price' => $grandTotal,
                'total_cogs' => $totalCogs,
                'gross_profit' => round($grandTotal - $shipping - $totalCogs, 2),
                'refund_total' => 0,
                'exchange_due_total' => 0,
                'currency' => 'BDT',
                'shipping_address_snapshot' => $snapshotAddress,
                'billing_address_snapshot' => $snapshotAddress,
                'customer_note' => $source === 'social_commerce' ? 'Created manually from Facebook/WhatsApp conversation.' : null,
                'shop_id' => $shop->id,
                'created_by' => $creator->id,
                'assigned_to' => $source === 'ecommerce' ? $employees[$i % $employees->count()]->id : $creator->id,
                'order_date' => $orderedAt,
                'paid_amount' => $paidAmount,
                'due_amount' => $dueAmount,
                'source_reference' => 'SEED-' . strtoupper($source) . '-' . str_pad((string) $i, 4, '0', STR_PAD_LEFT),
                'priority' => $i % 17 === 0 ? 'urgent' : 'normal',
                'delivery_status' => in_array($status, ['delivered', 'completed'], true) ? 'delivered' : $status,
                'placed_at' => $orderedAt,
                'confirmed_at' => in_array($status, ['confirmed', 'processing', 'delivered', 'completed'], true) ? $orderedAt->copy()->addMinutes(30) : null,
                'shipped_at' => in_array($status, ['delivered', 'completed'], true) && $source !== 'pos' ? $orderedAt->copy()->addHours(6) : null,
                'delivered_at' => in_array($status, ['delivered', 'completed'], true) ? $orderedAt->copy()->addHours($source === 'pos' ? 1 : 24) : null,
                'cancelled_at' => $status === 'cancelled' ? $orderedAt->copy()->addHours(2) : null,
                'ordered_products' => collect($linePayloads)->map(fn ($row) => [
                    'product_id' => $row['product']->id,
                    'variant_id' => $row['variant']?->id,
                    'name' => $row['product']->name,
                    'sku' => $row['variant']?->sku ?: $row['product']->sku,
                    'quantity' => $row['quantity'],
                    'unit_price' => $row['unitPrice'],
                ])->values()->all(),
                'customer_details' => ['name' => $customerName, 'phone' => $customerPhone, 'email' => $customer?->email],
                'address' => $snapshotAddress,
                'created_at' => $orderedAt,
                'updated_at' => $orderedAt,
            ]);
            $order->forceFill(['created_at' => $orderedAt, 'updated_at' => $orderedAt])->saveQuietly();

            foreach ($linePayloads as $lineIndex => $row) {
                $lineDiscount = $subtotal > 0 ? round($discount * ($row['lineSubtotal'] / $subtotal), 2) : 0;
                $lineGrand = round($row['lineSubtotal'] - $lineDiscount, 2);
                OrderItem::create([
                    'order_id' => $order->id,
                    'product_id' => $row['product']->id,
                    'variant_id' => $row['variant']?->id,
                    'category_id' => $row['product']->category_id,
                    'product_snapshot' => [
                        'name' => $row['product']->name,
                        'sku' => $row['variant']?->sku ?: $row['product']->sku,
                        'image' => $row['product']->primary_image_url,
                        'variation' => $row['variant']?->attribute_values,
                    ],
                    'quantity' => $row['quantity'],
                    'unit_price' => $row['unitPrice'],
                    'unit_cost' => $row['unitCost'],
                    'tax_rate' => 0,
                    'discount_amount' => $lineDiscount,
                    'line_subtotal' => $row['lineSubtotal'],
                    'line_discount_total' => $lineDiscount,
                    'line_tax_total' => 0,
                    'line_total' => $lineGrand,
                    'line_grand_total' => $lineGrand,
                    'discount_snapshot' => $lineDiscount > 0 ? ['type' => $applyCoupon ? 'promotion' : 'manual', 'amount' => $lineDiscount] : [],
                    'cogs_total' => round($row['unitCost'] * $row['quantity'], 2),
                    'gross_profit' => round($lineGrand - ($row['unitCost'] * $row['quantity']), 2),
                    'item_status' => $status,
                    'created_at' => $orderedAt,
                    'updated_at' => $orderedAt,
                ]);
            }

            if ($paidAmount > 0) {
                Payment::create([
                    'order_id' => $order->id,
                    'payment_method' => $paymentMethod,
                    'gateway' => in_array($paymentMethod, ['bkash', 'nagad', 'card'], true) ? $paymentMethod : null,
                    'gateway_transaction_id' => 'SEEDPAY-' . str_pad((string) $i, 6, '0', STR_PAD_LEFT),
                    'amount' => $paidAmount,
                    'currency' => 'BDT',
                    'status' => $paymentStatus === 'paid' ? 'completed' : 'partial',
                    'paid_at' => $orderedAt->copy()->addMinutes(5),
                    'received_by' => $creator->id,
                    'payment_reference' => 'SEED-PAY-' . str_pad((string) $i, 4, '0', STR_PAD_LEFT),
                    'refunded_amount' => 0,
                ]);
            }

            OrderStatusHistory::create([
                'order_id' => $order->id,
                'from_status' => null,
                'to_status' => $status,
                'changed_by' => $creator->id,
                'note' => 'Seeded order status history.',
                'created_at' => $orderedAt,
            ]);

            if ($applyCoupon) {
                CouponApplication::create([
                    'order_id' => $order->id,
                    'coupon_id' => $coupon->id,
                    'code' => $coupon->code,
                    'promotion_type' => $coupon->promotion_type,
                    'visibility' => $coupon->visibility,
                    'discount_scope' => $coupon->discount_scope,
                    'base_amount' => $subtotal,
                    'item_discount_amount' => $discount,
                    'shipping_discount_amount' => 0,
                    'discount_amount' => $discount,
                    'snapshot' => ['title' => $coupon->title, 'value' => $coupon->value],
                    'created_at' => $orderedAt,
                    'updated_at' => $orderedAt,
                ]);
                $couponUses++;
            }

            $orders->push($order->fresh('items', 'payments'));
        }

        if ($coupon) {
            $coupon->update(['used_count' => $couponUses]);
        }

        return $orders;
    }

    private function seedReturns($orders, $products, Shop $shop, User $admin): void
    {
        $eligible = $orders->filter(fn (Order $order) => in_array($order->status, ['delivered', 'completed'], true) && $order->items->isNotEmpty())->take(20)->values();

        foreach ($eligible as $index => $order) {
            $isRefund = $index < 10;
            $item = $order->items->first();
            $amount = round((float) $item->line_grand_total / max(1, (int) $item->quantity), 2);
            $createdAt = Carbon::parse($order->created_at)->addDays(2);
            $exchangeProduct = $products[($index * 7 + 3) % $products->count()];
            $exchangeVariant = $exchangeProduct->productVariants->first();
            $exchangePrice = (float) ($exchangeVariant?->sale_price ?: $exchangeVariant?->price ?: $exchangeProduct->sale_price ?: $exchangeProduct->selling_price ?: $amount);
            $difference = round($exchangePrice - $amount, 2);

            $return = ReturnRequest::create([
                'rr_number' => 'RR-DEMO-' . str_pad((string) ($index + 1), 3, '0', STR_PAD_LEFT),
                'order_id' => $order->id,
                'customer_id' => $order->customer_id,
                'type' => $isRefund ? 'return' : 'exchange',
                'status' => 'completed',
                'reason' => $isRefund ? 'Size or product preference changed' : 'Customer requested another variation',
                'customer_note' => 'Demonstration return/exchange request.',
                'admin_note' => 'Inspected and completed by seeded administrator.',
                'approved_by' => $admin->id,
                'approved_at' => $createdAt->copy()->addHour(),
                'refund_total' => $isRefund ? $amount : max(0, -$difference),
                'exchange_credit_total' => $isRefund ? 0 : $amount,
                'exchange_due_total' => $isRefund ? 0 : max(0, $difference),
                'promotion_adjustment_total' => 0,
                'resolved_at' => $createdAt->copy()->addHours(3),
                'shop_id' => $shop->id,
                'created_by' => $admin->id,
                'resolution_type' => $isRefund ? 'refund' : 'exchange',
                'refund_method' => $isRefund ? ($order->payment_method ?: 'cash') : null,
                'restock_strategy' => $index % 4 === 0 ? 'damaged' : 'sellable',
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
            ]);
            $return->forceFill(['created_at' => $createdAt, 'updated_at' => $createdAt])->saveQuietly();

            ReturnRequestItem::create([
                'return_request_id' => $return->id,
                'order_item_id' => $item->id,
                'quantity' => 1,
                'reason' => $return->reason,
                'condition_note' => $index % 4 === 0 ? 'Packaging opened; route to damaged inspection.' : 'Unused and sellable.',
                'exchange_product_id' => $isRefund ? null : $exchangeProduct->id,
                'exchange_variant_id' => $isRefund ? null : $exchangeVariant?->id,
                'unit_price' => $amount,
                'line_subtotal' => $amount,
                'prorated_discount_amount' => 0,
                'refundable_amount' => $isRefund ? $amount : 0,
                'exchange_unit_price' => $isRefund ? 0 : $exchangePrice,
                'exchange_line_total' => $isRefund ? 0 : $exchangePrice,
                'exchange_price_difference' => $isRefund ? 0 : $difference,
                'exchange_amount_due' => $isRefund ? 0 : max(0, $difference),
                'exchange_refund_due' => $isRefund ? 0 : max(0, -$difference),
            ]);

            ReturnStatusHistory::create([
                'return_request_id' => $return->id,
                'from_status' => 'approved',
                'to_status' => 'completed',
                'changed_by' => $admin->id,
                'note' => $isRefund ? 'Refund completed.' : 'Exchange completed.',
                'created_at' => $createdAt->copy()->addHours(3),
            ]);

            if ($isRefund) {
                $item->update([
                    'refunded_quantity' => 1,
                    'refunded_amount' => $amount,
                    'item_status' => 'refunded',
                ]);
                $order->increment('refund_total', $amount);
                $payment = $order->payments->first();
                if ($payment) {
                    $payment->update([
                        'refunded_amount' => $amount,
                        'refund_status' => $amount >= (float) $payment->amount ? 'full' : 'partial',
                    ]);
                }
            } else {
                $item->update(['exchanged_quantity' => 1, 'item_status' => 'exchanged']);
                if ($difference > 0) {
                    $order->increment('exchange_due_total', $difference);
                }
            }
        }
    }

    private function seedTransactions(Shop $shop, User $admin, $employees): void
    {
        $expenseReasons = [
            ['Utilities', 'Electricity bill for the retail store'],
            ['Delivery', 'Local delivery and courier settlement'],
            ['Maintenance', 'Air conditioner and lighting maintenance'],
            ['Marketing', 'Social media campaign and product photography'],
            ['Supplies', 'Packaging bags, tape and invoice paper'],
            ['Transport', 'Product collection transport expense'],
        ];

        for ($i = 1; $i <= 30; $i++) {
            [$category, $reason] = $expenseReasons[($i - 1) % count($expenseReasons)];
            $type = $i % 10 === 0 ? 'income' : 'expense';
            BusinessTransaction::create([
                'transaction_number' => 'TXN-SEED-' . str_pad((string) $i, 4, '0', STR_PAD_LEFT),
                'shop_id' => $shop->id,
                'type' => $type,
                'category' => $type === 'income' ? 'Other income' : $category,
                'amount' => $type === 'income' ? 1500 + ($i * 50) : 300 + (($i * 173) % 3700),
                'payment_method' => ['cash', 'bkash', 'bank'][$i % 3],
                'reason' => $type === 'income' ? 'Recovered delivery adjustment and miscellaneous income.' : $reason,
                'reference' => 'SEED-TXN-' . str_pad((string) $i, 3, '0', STR_PAD_LEFT),
                'occurred_at' => now()->subDays(30 - $i)->setTime(12, ($i * 3) % 60),
                'status' => 'recorded',
                'created_by' => $employees[($i - 1) % $employees->count()]->id,
                'approved_by' => $admin->id,
                'meta' => ['seeded' => true],
                'created_at' => now()->subDays(30 - $i),
                'updated_at' => now()->subDays(30 - $i),
            ]);
        }
    }

    private function resetEverySellableSkuToFifty($products, Shop $shop, User $admin): void
    {
        foreach ($products as $product) {
            if ($product->productVariants->isNotEmpty()) {
                Inventory::updateOrCreate(
                    ['product_id' => $product->id, 'variant_id' => null, 'shop_id' => $shop->id],
                    ['quantity' => 0, 'reserved' => 0, 'low_stock_threshold' => 5, 'updated_at' => now()]
                );
                foreach ($product->productVariants as $variant) {
                    $inventory = Inventory::updateOrCreate(
                        ['product_id' => $product->id, 'variant_id' => $variant->id, 'shop_id' => $shop->id],
                        ['quantity' => 50, 'reserved' => 0, 'low_stock_threshold' => 5, 'updated_at' => now()]
                    );
                    ProductBatch::updateOrCreate(
                        ['batch_reference' => 'SEED-DEMO-' . $shop->id . '-' . $product->id . '-' . $variant->id],
                        [
                            'product_id' => $product->id,
                            'variant_id' => $variant->id,
                            'shop_id' => $shop->id,
                            'count' => 50,
                            'initial_quantity' => 50,
                            'cost_price' => $variant->cost_price ?: $product->cost_price ?: 0,
                            'selling_price' => $variant->sale_price ?: $variant->price ?: $product->selling_price ?: 0,
                            'created_by' => $admin->id,
                            'note' => 'Direct batch generated by HajjMartDemoOperationsSeeder.',
                            'received_at' => now(),
                        ]
                    );
                    $variant->update([
                        'in_stock' => true,
                        'purchasable' => true,
                        'available_for_purchase' => true,
                    ]);
                    StockMovement::create([
                        'inventory_id' => $inventory->id,
                        'type' => 'adjustment',
                        'quantity_change' => 0,
                        'reference_type' => 'database_seed',
                        'reference_id' => null,
                        'note' => 'Seeder normalized this variation to 50 units.',
                        'created_by' => $admin->id,
                        'created_at' => now(),
                        'shop_id' => $shop->id,
                        'balance_after' => 50,
                        'reason_code' => 'seed_stock_50',
                    ]);
                }
            } else {
                $inventory = Inventory::updateOrCreate(
                    ['product_id' => $product->id, 'variant_id' => null, 'shop_id' => $shop->id],
                    ['quantity' => 50, 'reserved' => 0, 'low_stock_threshold' => 5, 'updated_at' => now()]
                );
                ProductBatch::updateOrCreate(
                    ['batch_reference' => 'SEED-DEMO-' . $shop->id . '-' . $product->id . '-0'],
                    [
                        'product_id' => $product->id,
                        'variant_id' => null,
                        'shop_id' => $shop->id,
                        'count' => 50,
                        'initial_quantity' => 50,
                        'cost_price' => $product->cost_price ?: 0,
                        'selling_price' => $product->sale_price ?: $product->selling_price ?: 0,
                        'created_by' => $admin->id,
                        'note' => 'Direct batch generated by HajjMartDemoOperationsSeeder.',
                        'received_at' => now(),
                    ]
                );
                StockMovement::create([
                    'inventory_id' => $inventory->id,
                    'type' => 'adjustment',
                    'quantity_change' => 0,
                    'reference_type' => 'database_seed',
                    'reference_id' => null,
                    'note' => 'Seeder normalized this product to 50 units.',
                    'created_by' => $admin->id,
                    'created_at' => now(),
                    'shop_id' => $shop->id,
                    'balance_after' => 50,
                    'reason_code' => 'seed_stock_50',
                ]);
            }
            $product->updateTotalCount();
        }
    }

    private function seedDailySummaries(): void
    {
        for ($daysAgo = 29; $daysAgo >= 0; $daysAgo--) {
            $date = now()->subDays($daysAgo)->toDateString();
            $orders = Order::whereDate('created_at', $date)->get();
            $valid = $orders->where('status', '!=', 'cancelled');
            DailySalesSummary::updateOrCreate(
                ['date' => $date],
                [
                    'total_orders' => $orders->count(),
                    'cancelled_orders' => $orders->where('status', 'cancelled')->count(),
                    'total_revenue' => $valid->sum(fn ($order) => (float) $order->grand_total),
                    'total_cogs' => $valid->sum(fn ($order) => (float) $order->total_cogs),
                    'gross_profit' => $valid->sum(fn ($order) => (float) $order->gross_profit),
                    'total_refunds' => $valid->sum(fn ($order) => (float) $order->refund_total),
                    'total_items_sold' => OrderItem::whereIn('order_id', $valid->pluck('id'))->sum('quantity'),
                    'district_breakdown' => $valid->groupBy('checkout_district')->map->count()->all(),
                ]
            );
        }
    }

    private function orderStatus(int $index): string
    {
        if ($index % 20 === 0) return 'cancelled';
        if ($index % 11 === 0) return 'pending';
        if ($index % 7 === 0) return 'processing';
        if ($index % 5 === 0) return 'confirmed';
        return $index % 2 === 0 ? 'completed' : 'delivered';
    }

    private function paymentState(int $index, string $status, float $grandTotal): array
    {
        if ($status === 'cancelled' || $status === 'pending') return ['unpaid', 0.0];
        if ($index % 9 === 0) return ['partial', round($grandTotal * 0.6, 2)];
        return ['paid', $grandTotal];
    }
}
