"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { useStore } from "@/context/store-context";
import { adminRequest, pageRows } from "@/lib/admin-api";
import { demoReturns } from "@/lib/admin-demo";
import type { AdminPayment, AdminReturn, Paginated } from "@/lib/admin-types";
import { formatPrice } from "@/lib/utils";
import { AdminProductImage } from "@/components/admin/admin-product-image";
import { AdminButton, AdminIcon, AdminSelect, Drawer, Field, FormGrid, PageHeader, Panel, SearchField, StatusBadge, TableShell, formatDate } from "@/components/admin/admin-ui";

const displayStatus=(value:string)=>value==="pending"?"requested":value==="exchanged"?"completed":value;

export default function ReturnsPage() {
  const {token,selectedStoreId,demoMode}=useAdmin(); const {notify}=useStore();
  const [rows,setRows]=useState<AdminReturn[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<AdminReturn|null>(null); const [refundOpen,setRefundOpen]=useState(false); const [disposition,setDisposition]=useState<"sellable"|"damaged"|"do_not_restock">("sellable"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(demoMode){setRows(demoReturns);setError(null);return}if(!token)return;const controller=new AbortController();setError(null);void adminRequest<Paginated<AdminReturn>|AdminReturn[]>("/return-requests?per_page=100",{token,signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setRows(pageRows(data))}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Return requests could not be loaded.")});return()=>controller.abort()},[token,demoMode]);
  const filtered=useMemo(()=>rows.filter(r=>`${r.rr_number} ${r.order?.order_number} ${r.order?.checkout_name}`.toLowerCase().includes(search.toLowerCase())&&(status==="all"||displayStatus(r.status)===status)&&(selectedStoreId==="all"||r.order?.shop?.id===selectedStoreId)),[rows,search,status,selectedStoreId]);
  const sync=(value:AdminReturn)=>{setRows(c=>c.map(r=>r.id===value.id?value:r));setSelected(value)};
  async function action(kind:"approve"|"reject"){if(!selected)return;setBusy(true);setError(null);try{let value:AdminReturn={...selected,status:kind==="approve"?"approved":"rejected"};if(!demoMode&&token)value=await adminRequest<AdminReturn>(`/return-requests/${selected.id}/${kind}`,{method:"POST",token,body:{note:kind==="approve"?"Approved after order review.":"Rejected after policy review."}});sync(value);notify(kind==="approve"?"Return/exchange approved. Stock remains unchanged until physical receipt.":"Return/exchange rejected with an audit note.");}catch(reason){setError(reason instanceof Error?reason.message:"Return workflow could not be updated.");}finally{setBusy(false)}}
  async function receive(){if(!selected)return;setBusy(true);setError(null);try{let value:AdminReturn;if(demoMode||!token)value={...selected,status:selected.type==="exchange"?"exchanged":"received",restock_strategy:disposition};else value=await adminRequest<AdminReturn>(`/return-requests/${selected.id}/receive`,{method:"POST",token,body:{restock_strategy:disposition,restock_returned_items:disposition==="sellable",note:`Inspected and classified as ${disposition}.`}});sync(value);notify(disposition==="sellable"?"Returned quantity received into sellable inventory.":"Returned quantity received without adding it to available stock.");}catch(reason){setError(reason instanceof Error?reason.message:"Returned product could not be received.");}finally{setBusy(false)}}
  async function refund(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);const paymentId=Number(data.get("payment_id"));const amount=Number(data.get("amount"));const note=String(data.get("note"));setBusy(true);setError(null);try{if(!demoMode&&token){await adminRequest<AdminPayment>(`/payments/${paymentId}/refund`,{method:"POST",token,body:{amount}});const completed=await adminRequest<AdminReturn>(`/return-requests/${selected.id}/complete`,{method:"POST",token,body:{resolution_type:"refund",refund_method:String(data.get("refund_method")||"original_payment"),note}});sync(completed);}else sync({...selected,status:"completed",resolution_type:"refund",refund_method:String(data.get("refund_method"))});setRefundOpen(false);notify("Refund posted to the original payment ledger and the return workflow was completed.");}catch(reason){setError(reason instanceof Error?reason.message:"Refund could not be completed.");}finally{setBusy(false)}}
  const refundablePayments=selected?.order?.payments?.filter(p=>Number(p.amount)-Number(p.refunded_amount||0)>0)||[];
  return <>
    <PageHeader title="Returns, exchange & refunds" description="A controlled workflow from request to approval, physical receipt, stock disposition, replacement and refund—without losing the original order trail." actions={<a href="/admin/orders"><AdminButton icon="plus">Start from order</AdminButton></a>}/>{error&&<p className="admin-form-error">{error}</p>}
    <div className="admin-inline-metrics"><div><span>Open requests</span><strong>{rows.filter(r=>!["completed","rejected","exchanged"].includes(r.status)).length}</strong></div><div><span>Awaiting receipt</span><strong>{rows.filter(r=>r.status==="approved").length}</strong></div><div><span>Refund exposure</span><strong>{formatPrice(rows.reduce((s,r)=>s+Number(r.refund_total||0),0))}</strong></div><div><span>Exchanges</span><strong>{rows.filter(r=>r.type==="exchange").length}</strong></div></div>
    <Panel><div className="admin-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Request, order or customer…"/><AdminSelect value={status} onChange={setStatus}><option value="all">All statuses</option>{["requested","approved","received","completed","rejected"].map(s=><option key={s}>{s}</option>)}</AdminSelect></div><TableShell><thead><tr><th>Request</th><th>Order / customer</th><th>Type</th><th>Reason</th><th>Status</th><th className="align-right">Financial effect</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} onClick={()=>{setSelected(r);setDisposition((r.restock_strategy as typeof disposition)||"sellable")}} className="admin-clickable-row"><td><span className="admin-primary-cell">{r.rr_number}<small>{formatDate(r.created_at,true)}</small></span></td><td><strong>{r.order?.order_number}</strong><small>{r.order?.checkout_name} · {r.order?.shop?.name}</small></td><td><span className="admin-source"><AdminIcon name="returns" size={14}/>{r.type}</span></td><td><span className="admin-truncate">{r.reason}</span></td><td><StatusBadge value={displayStatus(r.status)}/></td><td className="align-right"><strong>{r.type==="return"?formatPrice(r.refund_total||0):formatPrice(r.exchange_due_total||0)}</strong><small>{r.type==="return"?"potential refund":"exchange adjustment"}</small></td><td className="align-right"><button className="admin-icon-button"><AdminIcon name="chevron"/></button></td></tr>)}</tbody></TableShell></Panel>
    <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.rr_number||"Return request"} subtitle={selected?.order?.order_number} wide>{selected&&<div className="admin-stack"><div className="admin-detail-status"><div><span>Request type</span><strong>{selected.type}</strong></div><div><span>Workflow status</span><StatusBadge value={displayStatus(selected.status)}/></div><div><span>{selected.type==="return"?"Refund amount":"Exchange due"}</span><strong>{formatPrice(selected.type==="return"?selected.refund_total:selected.exchange_due_total)}</strong></div></div><div className="admin-return-flow">{["requested","approved","received","completed"].map((step,index)=>{const current=["requested","approved","received","completed"].indexOf(displayStatus(selected.status));return <div key={step} className={index<=current?"done":""}><span>{index<current?<AdminIcon name="check"/>:index+1}</span><p>{step}<small>{index===0?"Customer/agent request":index===1?"Manager decision":index===2?"Physical inspection":"Refund or replacement"}</small></p></div>})}</div><Panel title="Reason and returned items"><p className="admin-long-copy">{selected.reason}</p><div className="admin-order-lines">{selected.items?.map(item=><div key={item.id}><span className="admin-line-image"><AdminProductImage product={item.order_item?.product}/></span><div><strong>{item.order_item?.product.name}</strong><small>{item.order_item?.product.sku} · Qty {item.quantity}</small></div><span>Refundable</span><b>{formatPrice(item.refundable_amount||0)}</b></div>)}</div></Panel>{selected.status==="approved"&&<Panel title="Stock disposition"><div className="admin-choice-cards"><label><input type="radio" name="disposition" checked={disposition==="sellable"} onChange={()=>setDisposition("sellable")}/><span><AdminIcon name="check"/><strong>Return to saleable stock</strong><small>Only after inspection confirms sellable condition.</small></span></label><label><input type="radio" name="disposition" checked={disposition==="damaged"} onChange={()=>setDisposition("damaged")}/><span><AdminIcon name="warning"/><strong>Damaged / quarantine</strong><small>Do not add to normal available inventory.</small></span></label></div></Panel>}{error&&<p className="admin-form-error">{error}</p>}<div className="admin-action-strip">{["requested","pending"].includes(selected.status)&&<><AdminButton icon="check" disabled={busy} onClick={()=>action("approve")}>{busy?"Updating…":"Approve request"}</AdminButton><AdminButton variant="danger" disabled={busy} onClick={()=>action("reject")}>Reject</AdminButton></>}{selected.status==="approved"&&<AdminButton icon="inventory" disabled={busy} onClick={receive}>{busy?"Receiving…":"Receive product"}</AdminButton>}{selected.status==="received"&&selected.type==="return"&&<AdminButton icon="money" onClick={()=>setRefundOpen(true)}>Process refund</AdminButton>}</div></div>}</Drawer>
    <Drawer open={refundOpen} onClose={()=>!busy&&setRefundOpen(false)} title="Process refund" subtitle={selected?.rr_number}>{selected&&<form className="admin-stack" onSubmit={refund}><div className="admin-payment-total"><span>Refund payable</span><strong>{formatPrice(selected.refund_total||0)}</strong></div><FormGrid><Field label="Original payment"><select name="payment_id" required>{refundablePayments.map(p=><option key={p.id} value={p.id}>{p.payment_method} · {formatPrice(Number(p.amount)-Number(p.refunded_amount||0))} refundable</option>)}</select></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" max={Number(selected.refund_total||0)} defaultValue={Number(selected.refund_total||0)} required/></Field></FormGrid><Field label="Refund method"><select name="refund_method"><option value="original_payment">Original payment method</option><option value="cash">Cash</option><option value="bkash">bKash</option><option value="bank">Bank</option></select></Field><Field label="Completion note" required><textarea name="note" required rows={3}/></Field>{!refundablePayments.length&&<p className="admin-form-error">No refundable payment is attached to this order.</p>}{error&&<p className="admin-form-error">{error}</p>}<AdminButton icon="check" disabled={busy||!refundablePayments.length}>{busy?"Processing…":"Complete refund"}</AdminButton></form>}</Drawer>
  </>;
}
