"use client";

import { useEffect, useMemo, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { adminRequest, pageRows, queryString } from "@/lib/admin-api";
import { demoActivity } from "@/lib/admin-demo";
import type { ActivityLog, Paginated } from "@/lib/admin-types";
import { AdminButton, AdminIcon, AdminSelect, PageHeader, Panel, SearchField, formatDate } from "@/components/admin/admin-ui";

export default function ActivityPage(){
 const {token,demoMode,selectedStoreId}=useAdmin();const [search,setSearch]=useState("");const [module,setModule]=useState("all");const [logs,setLogs]=useState<ActivityLog[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(demoMode){setLogs(demoActivity);setError(null);return}if(!token)return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setError(null);void adminRequest<Paginated<ActivityLog>>(`/activity-logs${queryString({q:search,module:module==="all"?undefined:module,shop_id:selectedStoreId==="all"?undefined:selectedStoreId,per_page:80})}`,{token,signal:controller.signal}).then(data=>setLogs(pageRows(data))).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Activity records could not be loaded.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},180);return()=>{window.clearTimeout(timer);controller.abort()}},[demoMode,token,search,module,selectedStoreId]);
 const rows=useMemo(()=>demoMode?logs.filter(r=>`${r.description} ${r.user?.name}`.toLowerCase().includes(search.toLowerCase())&&(module==="all"||r.module===module)):logs,[demoMode,logs,search,module]);const modules=[...new Set([...demoActivity,...logs].map(r=>r.module))];
 function exportCsv(){const data=["Time,Module,Action,Employee,Store,Description",...rows.map(r=>[r.created_at,r.module,r.action,r.user?.name||"System",r.shop?.name||"All stores",r.description].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");const url=URL.createObjectURL(new Blob([data],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="hajjmart-activity-log.csv";link.click();URL.revokeObjectURL(url)}
 return <><PageHeader title="Activity log" description="A human-readable audit trail for sensitive actions: sales, payments, stock changes, batch confirmations, refunds, employee access and configuration." actions={<AdminButton variant="secondary" icon="download" onClick={exportCsv}>Export audit log</AdminButton>}/>{error&&<p className="admin-form-error">{error}</p>}<Panel><div className="admin-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Action, employee, order or reference…"/><AdminSelect value={module} onChange={setModule}><option value="all">All modules</option>{modules.map(m=><option key={m}>{m}</option>)}</AdminSelect></div>{loading&&<p className="admin-picker-loading">Refreshing audit records…</p>}<div className="admin-audit-timeline">{rows.map((row,index)=><article key={row.id}><div className="admin-audit-time"><strong>{formatDate(row.created_at,true)}</strong><small>{index===0?"Latest activity":"Earlier"}</small></div><span className={`module-${row.module.toLowerCase().replaceAll(" ","-")}`}><AdminIcon name={row.module.toLowerCase().includes("order")?"orders":row.module.toLowerCase().includes("payment")?"money":row.module.toLowerCase().includes("inventory")?"inventory":row.module.toLowerCase().includes("return")?"returns":row.module.toLowerCase().includes("people")||row.module.toLowerCase().includes("role")?"employees":"activity"}/></span><div><p><strong>{row.user?.name||"System"}</strong> · {row.action.replaceAll("_"," ")}</p><h3>{row.description}</h3><small>{row.module} · {row.shop?.name||"All stores"}</small></div><button title="Structured before/after values are retained by the API"><AdminIcon name="eye"/><span>Inspect change</span></button></article>)}</div>{!rows.length&&<div className="admin-cart-empty"><AdminIcon name="activity" size={30}/><strong>No matching activity</strong><small>Change the search or module filter.</small></div>}</Panel><Panel title="Audit design principles"><div className="admin-process-cards"><div><span>01</span><strong>Who</strong><p>The authenticated employee, role and store.</p></div><div><span>02</span><strong>What</strong><p>Human-readable action plus the linked record.</p></div><div><span>03</span><strong>Before / after</strong><p>Structured values for financial and stock changes.</p></div><div><span>04</span><strong>Why</strong><p>Mandatory reasons for cancellation, adjustment and refund.</p></div></div></Panel></>;
}
