"use client";

import { FormEvent, useEffect, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { useStore } from "@/context/store-context";
import { adminRequest } from "@/lib/admin-api";
import type { AdminStore } from "@/lib/admin-types";
import { formatPrice } from "@/lib/utils";
import { AdminButton, AdminIcon, Drawer, Field, FormGrid, PageHeader, Panel, StatusBadge } from "@/components/admin/admin-ui";

export default function StoresPage(){
 const {stores:initialStores,token,demoMode,refreshSession}=useAdmin(); const {notify}=useStore(); const [stores,setStores]=useState<AdminStore[]>(initialStores); const [selected,setSelected]=useState<AdminStore|null>(null); const [createOpen,setCreateOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>setStores(initialStores),[initialStores]);
 
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError(null);try{const input={name:String(d.get("name")),code:String(d.get("code")).toUpperCase(),address:String(d.get("address")),phone:String(d.get("phone")||""),email:String(d.get("email")||""),is_active:true,is_default:d.get("is_default")==="on"};let store:AdminStore;if(demoMode||!token){store={id:Date.now(),...input,slug:input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),employees_count:0,orders_count:0,inventory_units:0,sales_30_days:0}}else{store=await adminRequest<AdminStore>("/stores",{method:"POST",token,body:input});await refreshSession()}setStores(c=>input.is_default?[...c.map(s=>({...s,is_default:false})),store]:[...c,store]);setCreateOpen(false);notify("Store created. It can now hold inventory, employees and orders.")}catch(reason){setError(reason instanceof Error?reason.message:"Store could not be created.")}finally{setBusy(false)}}
 async function toggleStore(){if(!selected)return;setBusy(true);setError(null);try{const nextActive=!selected.is_active;let updated:AdminStore={...selected,is_active:nextActive};if(!demoMode&&token)updated=await adminRequest<AdminStore>(`/stores/${selected.id}`,{method:"PUT",token,body:{is_active:nextActive}});setSelected(updated);setStores(c=>c.map(s=>s.id===updated.id?updated:s));notify(`Store ${nextActive?"activated":"deactivated"}.`)}catch(reason){setError(reason instanceof Error?reason.message:"Store status could not be changed.")}finally{setBusy(false)}}
 return <><PageHeader title="Stores" description="Operate one store or many without changing workflows. Inventory, orders, employees and reporting stay location-aware while Super Admin sees the consolidated business." actions={<AdminButton icon="plus" onClick={()=>setCreateOpen(true)}>Add store</AdminButton>}/>{error&&<p className="admin-form-error">{error}</p>}
 <div className="admin-store-grid">{stores.map(store=><article key={store.id} onClick={()=>setSelected(store)}><div className="admin-store-card-art"><div/><img src="/images/brand/hajjmart-logo.svg" alt="HajjMart"/><span className="admin-store-code">{store.code||"HM"}</span><StatusBadge value={store.is_active?"active":"inactive"}/></div><div className="admin-store-card-body"><p className="admin-eyebrow">{store.is_default?"Default fulfilment store":"HajjMart location"}</p><h2>{store.name}</h2><p>{store.address}</p><div><span><strong>{store.inventory_units||0}</strong><small>stock units</small></span><span><strong>{store.orders_count||0}</strong><small>orders</small></span><span><strong>{store.employees_count||0}</strong><small>employees</small></span></div><footer><strong>{formatPrice(store.sales_30_days||0)}</strong><small>last 30 days</small><AdminIcon name="chevron"/></footer></div></article>)}</div>
 <Panel title="How multi-store works" description="The same HajjMart installation remains simple for a single store and becomes location-aware when another store is added."><div className="admin-process-cards"><div><span>01</span><strong>Store-specific stock</strong><p>Every product balance and reservation belongs to a store.</p></div><div><span>02</span><strong>Order ownership</strong><p>POS and social orders use the employee’s store; e-commerce follows fulfilment rules.</p></div><div><span>03</span><strong>Controlled transfers</strong><p>Stock leaves the source on dispatch and reaches the destination on receipt.</p></div><div><span>04</span><strong>Consolidated reports</strong><p>Managers see their store while authorised leaders can see all locations.</p></div></div></Panel>
 <Drawer open={createOpen} onClose={()=>!busy&&setCreateOpen(false)} title="Create store" subtitle="A store can be a retail outlet, warehouse or single operational location."><form className="admin-stack" onSubmit={create}><FormGrid><Field label="Store name" required><input name="name" required/></Field><Field label="Store code" required><input name="code" required maxLength={8}/></Field><Field label="Phone"><input name="phone"/></Field><Field label="Email"><input name="email" type="email"/></Field></FormGrid><Field label="Address" required><textarea name="address" rows={4} required/></Field><label className="admin-checkbox"><input name="is_default" type="checkbox"/><span>Set as default fulfilment store</span></label>{error&&<p className="admin-form-error">{error}</p>}<AdminButton icon="check" disabled={busy}>{busy?"Creating…":"Create store"}</AdminButton></form></Drawer>
 <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.name||"Store"} subtitle={selected?.address || undefined}>{selected&&<div className="admin-stack"><div className="admin-detail-status"><div><span>Status</span><StatusBadge value={selected.is_active?"active":"inactive"}/></div><div><span>Store code</span><strong>{selected.code}</strong></div></div><Panel title="Operating profile"><div className="admin-detail-grid"><div><span>Manager</span><strong>{selected.manager?.name||"Not assigned"}</strong><small>Store-level approval owner</small></div><div><span>Contact</span><strong>{selected.phone||"—"}</strong><small>{selected.email}</small></div><div><span>Employees</span><strong>{selected.employees_count||0}</strong><small>assigned users</small></div><div><span>Available inventory</span><strong>{selected.inventory_units||0}</strong><small>physical units</small></div></div></Panel><div className="admin-action-strip"><AdminButton icon="edit" disabled={busy} onClick={toggleStore}>{selected.is_active?"Deactivate store":"Activate store"}</AdminButton><a href={`/admin/inventory?shop_id=${selected.id}`}><AdminButton variant="secondary" icon="inventory">View inventory</AdminButton></a></div></div>}</Drawer></>;
}
