"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { useStore } from "@/context/store-context";
import { adminRequest, pageRows } from "@/lib/admin-api";
import { demoPromotions } from "@/lib/admin-demo";
import type { AdminPromotion, Paginated } from "@/lib/admin-types";
import { formatPrice } from "@/lib/utils";
import { AdminButton, AdminIcon, AdminSelect, Drawer, Field, FormGrid, PageHeader, Panel, SearchField, StatusBadge, formatDate } from "@/components/admin/admin-ui";

export default function PromotionsPage() {
  const {token,demoMode}=useAdmin(); const {notify}=useStore(); const [rows,setRows]=useState<AdminPromotion[]>([]); const [search,setSearch]=useState(""); const [type,setType]=useState("all"); const [createOpen,setCreateOpen]=useState(false); const [selected,setSelected]=useState<AdminPromotion|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(demoMode){setRows(demoPromotions);setError(null);return}if(!token)return;const controller=new AbortController();setError(null);void adminRequest<Paginated<AdminPromotion>|AdminPromotion[]>("/coupons?per_page=100",{token,signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setRows(pageRows(data))}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Promotions could not be loaded.")});return()=>controller.abort()},[token,demoMode]);
  const filtered=useMemo(()=>rows.filter(r=>`${r.code} ${r.title}`.toLowerCase().includes(search.toLowerCase())&&(type==="all"||r.promotion_type===type)),[rows,search,type]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const d=new FormData(event.currentTarget);setBusy(true);setError(null);try{const payload={code:String(d.get("code")).toUpperCase(),title:String(d.get("title")),description:String(d.get("description")||""),type:String(d.get("type")) as AdminPromotion["type"],value:Number(d.get("value")),visibility:String(d.get("visibility")) as AdminPromotion["visibility"],promotion_type:String(d.get("promotion_type")) as AdminPromotion["promotion_type"],discount_scope:String(d.get("discount_scope")||"cart"),is_active:true,auto_apply:d.get("auto_apply")==="on",stackable:d.get("stackable")==="on",starts_at:String(d.get("starts_at")||"")||null,expires_at:String(d.get("expires_at")||"")||null,usage_limit:Number(d.get("usage_limit"))||null,min_order_amount:Number(d.get("min_order_amount"))||0};let promotion:AdminPromotion;if(demoMode||!token)promotion={id:Date.now(),...payload,used_count:0};else promotion=await adminRequest<AdminPromotion>("/coupons",{method:"POST",token,body:payload});setRows(c=>[promotion,...c]);setCreateOpen(false);notify("Promotion created with visibility, eligibility and stacking rules.");}catch(reason){setError(reason instanceof Error?reason.message:"Promotion could not be created.");}finally{setBusy(false)}}
  async function toggle(){if(!selected)return;setBusy(true);setError(null);try{const active=!selected.is_active;let updated:AdminPromotion={...selected,is_active:active};if(!demoMode&&token)updated=await adminRequest<AdminPromotion>(`/coupons/${selected.id}`,{method:"PUT",token,body:{is_active:active}});setRows(c=>c.map(p=>p.id===updated.id?updated:p));setSelected(updated);notify(active?"Promotion activated.":"Promotion paused.");}catch(reason){setError(reason instanceof Error?reason.message:"Promotion status could not be updated.");}finally{setBusy(false)}}
  return <>
    <PageHeader title="Promotions" description="Run public sales that customers can discover automatically, or private coupon campaigns shared only with selected audiences." actions={<AdminButton icon="plus" onClick={()=>{setError(null);setCreateOpen(true)}}>Create promotion</AdminButton>}/>
    {error&&<p className="admin-form-error">{error}</p>}
    <div className="admin-promotion-summary"><div><span><AdminIcon name="promotions"/></span><strong>{rows.filter(r=>r.is_active).length}</strong><p>active campaigns</p></div><div><span><AdminIcon name="users"/></span><strong>{rows.reduce((s,r)=>s+(r.used_count||0),0)}</strong><p>redemptions</p></div><div><span><AdminIcon name="eye"/></span><strong>{rows.filter(r=>r.visibility==="public").length}</strong><p>public sales</p></div><div><span><AdminIcon name="roles"/></span><strong>{rows.filter(r=>r.visibility==="private").length}</strong><p>private coupons</p></div></div>
    <Panel><div className="admin-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Promotion code or title…"/><AdminSelect value={type} onChange={setType}><option value="all">All campaign types</option><option value="public_sale">Public sales</option><option value="private_coupon">Private coupons</option><option value="coupon">Coupons</option></AdminSelect></div><div className="admin-promotion-grid">{filtered.map(p=><article key={p.id} onClick={()=>setSelected(p)} className={!p.is_active?"inactive":""}><div className="admin-promo-top"><span className={p.visibility}><AdminIcon name={p.visibility==="public"?"eye":"roles"}/>{p.visibility}</span><StatusBadge value={p.is_active?"active":"inactive"}/></div><p className="admin-eyebrow">{p.promotion_type.replaceAll("_"," ")}</p><h3>{p.title||p.code}</h3><code>{p.code}</code><div className="admin-promo-value"><strong>{p.type==="percent"?`${p.value}%`:p.type==="fixed"?formatPrice(p.value):"Free"}</strong><span>{p.type==="free_shipping"?"shipping":p.discount_scope||"order discount"}</span></div><p>{p.description}</p><div className="admin-promo-progress"><span><i style={{width:`${Math.min(100,(p.used_count||0)/(p.usage_limit||Math.max(1,p.used_count||1))*100)}%`}}/></span><small>{p.used_count||0} used{p.usage_limit?` of ${p.usage_limit}`:""}</small></div><footer><span>{formatDate(p.starts_at)} → {formatDate(p.expires_at)}</span><AdminIcon name="chevron"/></footer></article>)}</div></Panel>
    <Drawer open={createOpen} onClose={()=>!busy&&setCreateOpen(false)} title="Create promotion" subtitle="Define who can see it, where it applies and whether it can stack." wide><form className="admin-stack" onSubmit={create}><Panel title="Campaign identity"><FormGrid><Field label="Campaign title" required><input name="title" required/></Field><Field label="Coupon / campaign code" required><input name="code" required placeholder="UMRAH10"/></Field><Field label="Campaign type"><select name="promotion_type"><option value="public_sale">Public sale</option><option value="private_coupon">Private coupon</option><option value="coupon">Standard coupon</option></select></Field><Field label="Visibility"><select name="visibility"><option value="public">Public</option><option value="private">Private</option></select></Field></FormGrid><Field label="Description"><textarea name="description" rows={3}/></Field></Panel><Panel title="Discount rules"><FormGrid columns={3}><Field label="Discount type"><select name="type"><option value="percent">Percentage</option><option value="fixed">Fixed amount</option><option value="free_shipping">Free shipping</option></select></Field><Field label="Value"><input name="value" type="number" min="0" defaultValue="5"/></Field><Field label="Discount scope"><select name="discount_scope"><option value="cart">Entire cart</option><option value="items">Eligible items</option><option value="shipping">Shipping</option></select></Field><Field label="Minimum order"><input name="min_order_amount" type="number" min="0" defaultValue="0"/></Field><Field label="Usage limit"><input name="usage_limit" type="number" min="0"/></Field><Field label="Starts"><input name="starts_at" type="date"/></Field><Field label="Expires"><input name="expires_at" type="date"/></Field></FormGrid><div className="admin-toggle-row"><label><input name="auto_apply" type="checkbox"/><span><strong>Auto apply</strong><small>Use the campaign when customer qualifies.</small></span></label><label><input name="stackable" type="checkbox"/><span><strong>Stackable</strong><small>Allow with another compatible promotion.</small></span></label></div></Panel>{error&&<p className="admin-form-error">{error}</p>}<AdminButton icon="check" disabled={busy}>{busy?"Publishing…":"Publish promotion"}</AdminButton></form></Drawer>
    <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title||"Promotion"} subtitle={selected?.code}>{selected&&<div className="admin-stack"><div className="admin-coupon-hero"><p>{selected.visibility} · {selected.promotion_type.replaceAll("_"," ")}</p><code>{selected.code}</code><strong>{selected.type==="percent"?`${selected.value}% off`:selected.type==="fixed"?`${formatPrice(selected.value)} off`:"Free shipping"}</strong></div><Panel title="Rules"><div className="admin-detail-grid"><div><span>Minimum order</span><strong>{formatPrice(selected.min_order_amount||0)}</strong></div><div><span>Usage</span><strong>{selected.used_count||0} / {selected.usage_limit||"∞"}</strong></div><div><span>Auto apply</span><strong>{selected.auto_apply?"Yes":"No"}</strong></div><div><span>Stackable</span><strong>{selected.stackable?"Yes":"No"}</strong></div></div></Panel><div className="admin-action-strip"><AdminButton icon="edit" onClick={()=>notify("Promotion edit workflow opened.")}>Edit campaign</AdminButton><AdminButton variant="secondary" disabled={busy} onClick={toggle}>{busy?"Updating…":selected.is_active?"Pause":"Activate"}</AdminButton></div></div>}</Drawer>
  </>;
}
