"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdmin } from "@/context/admin-context";
import { useStore } from "@/context/store-context";
import { adminRequest } from "@/lib/admin-api";
import { demoPermissions, demoRoles } from "@/lib/admin-demo";

const mutableDemoRoles = demoRoles.filter((role) => role.slug !== "super_admin");
import type { AdminPermission, AdminRole } from "@/lib/admin-types";
import { AdminButton, AdminIcon, Drawer, Field, PageHeader, Panel, StatusBadge } from "@/components/admin/admin-ui";

export default function RolesPage(){
 const {token,demoMode}=useAdmin(); const {notify}=useStore();
 const [roles,setRoles]=useState<AdminRole[]>(demoMode?mutableDemoRoles:[]); const [permissions,setPermissions]=useState<AdminPermission[]>(demoMode?demoPermissions:[]); const [selected,setSelected]=useState<AdminRole|null>(demoMode?mutableDemoRoles[0]:null); const [createOpen,setCreateOpen]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const groups=useMemo(()=>permissions.reduce<Record<string,AdminPermission[]>>((acc,p)=>{(acc[p.group] ||= []).push(p);return acc},{}),[permissions]);
 useEffect(()=>{if(demoMode){setRoles(mutableDemoRoles);setPermissions(demoPermissions);setSelected(mutableDemoRoles[0]);setError(null);return}if(!token)return;const controller=new AbortController();setError(null);void Promise.all([adminRequest<AdminRole[]>("/roles",{token,signal:controller.signal}),adminRequest<Record<string,AdminPermission[]>>("/permissions",{token,signal:controller.signal})]).then(([nextRoles,matrix])=>{if(controller.signal.aborted)return;const nextPermissions=Object.values(matrix).flat();setRoles(nextRoles);setSelected(current=>nextRoles.find(r=>r.id===current?.id)||nextRoles[0]||null);setPermissions(nextPermissions)}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Roles and permissions could not be loaded.")});return()=>controller.abort()},[demoMode,token]);
 function toggle(permissionId:number){if(!selected)return;if(selected.is_system&&selected.slug==="super_admin")return;const exists=selected?.permissions.some(p=>p.id===permissionId);const permission=permissions.find(p=>p.id===permissionId);if(!permission)return;const next={...selected,permissions:exists?selected.permissions.filter(p=>p.id!==permissionId):[...selected.permissions,permission]};setSelected(next);setRoles(c=>c.map(r=>r.id===next.id?next:r));}
 async function save(){if(!selected)return;setBusy(true);setError(null);try{if(!demoMode&&token){const saved=await adminRequest<AdminRole>(`/roles/${selected.id}`,{method:"PUT",token,body:{name:selected.name,description:selected.description,is_active:selected.is_active,permission_names:selected?.permissions.map(p=>p.name)}});setSelected(saved);setRoles(c=>c.map(r=>r.id===saved.id?saved:r))}notify("Role permission matrix saved and the access change was audited.")}catch(reason){setError(reason instanceof Error?reason.message:"Role access could not be saved.")}finally{setBusy(false)}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const name=String(d.get("name"));setBusy(true);setError(null);try{let role:AdminRole;if(demoMode||!token){role={id:Date.now(),name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"_"),description:String(d.get("description")),is_system:false,is_active:true,permissions:[],users_count:0}}else{role=await adminRequest<AdminRole>("/roles",{method:"POST",token,body:{name,description:String(d.get("description")||""),permission_names:[]}})}setRoles(c=>[...c,role]);setSelected(role);setCreateOpen(false);notify("Custom role created. Select and save its page permissions next.")}catch(reason){setError(reason instanceof Error?reason.message:"Role could not be created.")}finally{setBusy(false)}}
 return <><PageHeader title="Roles & page access" description="Build job-specific roles, assign permissions by workflow and keep the sidebar automatically limited to pages each employee may access." actions={<AdminButton icon="plus" onClick={()=>setCreateOpen(true)}>Create role</AdminButton>}/>
 {error&&<p className="admin-form-error">{error}</p>}<div className="admin-role-layout"><Panel title="Roles" description="System roles can be tuned but not accidentally deleted."><div className="admin-role-list">{roles.map(role=><button key={role.id} className={selected?.id===role.id?"active":""} onClick={()=>setSelected(role)}><span><AdminIcon name="roles"/></span><div><strong>{role.name}</strong><small>{role.users_count||0} employees · {role.permissions.length} permissions</small></div>{role.is_system&&<b>System</b>}<AdminIcon name="chevron"/></button>)}</div></Panel>
 {selected&&<Panel title={selected?.name||"Select a role"} description={selected?.description||"Configure role access."} action={<div className="admin-role-head-actions"><StatusBadge value={selected?.is_active?"active":"inactive"}/><AdminButton icon="check" disabled={busy} onClick={save}>{busy?"Saving…":"Save access"}</AdminButton></div>}><div className="admin-role-summary"><span><AdminIcon name="users"/><strong>{selected?.users_count||0}</strong><small>assigned employees</small></span><span><AdminIcon name="check"/><strong>{selected?.permissions.length||0}</strong><small>granted permissions</small></span><span><AdminIcon name="menu"/><strong>{new Set(selected?.permissions.map(p=>p.group)).size}</strong><small>visible modules</small></span></div><div className="admin-permission-matrix">{Object.entries(groups).map(([group,groupPermissions])=><section key={group}><div><h3>{group}</h3><p>{groupPermissions.filter(p=>selected?.permissions.some(s=>s.id===p.id)).length} of {groupPermissions.length} enabled</p></div><div>{groupPermissions.map(permission=>{const checked=selected?.permissions.some(p=>p.id===permission.id);return <label key={permission.id} className={checked?"checked":""}><input type="checkbox" checked={checked} onChange={()=>toggle(permission.id)} disabled={selected?.slug==="super_admin"}/><span><b>{checked?<AdminIcon name="check" size={13}/>:null}</b><strong>{permission.label}</strong><small>{permission.name}</small></span></label>})}</div></section>)}</div><p className="admin-callout"><AdminIcon name="activity"/>Every role change is recorded with the previous and new permission set. Existing sessions refresh access after a role update.</p></Panel>}</div>
 <Drawer open={createOpen} onClose={()=>!busy&&setCreateOpen(false)} title="Create custom role" subtitle="Start with no access, then enable only the workflows this job needs."><form className="admin-stack" onSubmit={create}><Field label="Role name" required><input name="name" required placeholder="Batch Receiving Executive"/></Field><Field label="Role description"><textarea name="description" rows={4} placeholder="What this employee is responsible for…"/></Field>{error&&<p className="admin-form-error">{error}</p>}<AdminButton icon="check" disabled={busy}>{busy?"Creating…":"Create role"}</AdminButton></form></Drawer></>;
}
