export type Paginated<T> = {
  data: T[];
  current_page?: number;
  per_page?: number;
  total?: number;
  last_page?: number;
};

export type AdminPermission = { id: number; name: string; group: string; label?: string | null; description?: string | null };
export type AdminRole = { id: number; name: string; slug: string; description?: string | null; is_system?: boolean; is_active?: boolean; permissions: AdminPermission[]; users_count?: number };
export type AdminStore = { id: number; name: string; code?: string | null; slug?: string | null; address?: string | null; phone?: string | null; email?: string | null; is_active?: boolean; is_default?: boolean; employees_count?: number; orders_count?: number; inventory_units?: number; sales_30_days?: string | number; manager?: { id: number; name: string } | null };
export type AdminUser = { id: number; name: string; email: string; phone?: string | null; role?: string | null; employee_code?: string | null; designation?: string | null; employment_type?: string | null; is_active?: boolean; shop_id?: number | null; shop?: AdminStore | null; roles?: AdminRole[]; permission_names?: string[]; role_names?: string[]; avatar?: string | null };
export type AdminProductVariant = { id: number; sku?: string | null; price?: string | number | null; sale_price?: string | number | null; retail_price?: string | number | null; wholesale_price?: string | number | null; regular_price?: string | number | null; cost_price?: string | number | null; attributes_json?: Record<string, string> | null; attribute_values?: Record<string, string> | string[] | null; in_stock?: boolean; is_active?: boolean; available_stock?: number; inventory?: { quantity: number; reserved: number; available?: number; shop_id?: number } | null };
export type AdminProductImage = { id?: number; path?: string | null; source_url?: string | null; downloaded_url?: string | null; url?: string | null; is_primary?: boolean; sort_order?: number };
export type AdminProduct = { id: number; name: string; slug: string; sku?: string | null; brand?: string | null; selling_price?: string | number | null; retail_price?: string | number | null; wholesale_price?: string | number | null; regular_price?: string | number | null; cost_price?: string | number | null; is_active?: boolean; is_featured?: boolean; image_src?: string[] | string | null; primary_image_url?: string | null; product_images?: AdminProductImage[]; available_stock?: number; stock_status?: string | null; categories?: Array<{ id: number; name: string; slug?: string }>; inventory?: Array<{ quantity: number; reserved: number; available?: number; shop_id?: number }>; product_variants?: AdminProductVariant[]; productVariants?: AdminProductVariant[] };
export type AdminProductBatch = { id: number; batch_reference: string; product_id: number; variant_id?: number | null; shop_id: number; count: number; initial_quantity: number; cost_price: string | number; selling_price: string | number; retail_price?: string | number | null; wholesale_price?: string | number | null; note?: string | null; received_at?: string | null; product: AdminProduct; variant?: AdminProductVariant | null; shop?: AdminStore | null; creator?: { id: number; name: string } | null };
export type InventoryRow = { id: number; product_id: number; variant_id?: number | null; shop_id: number; quantity: number; reserved: number; available: number; low_stock_threshold: number; bin_location?: string | null; stock_health: "healthy" | "low" | "out"; product: AdminProduct; variant?: { id: number; sku?: string | null } | null; shop: AdminStore };
export type AdminPayment = { id: number; amount: string | number; payment_method: string; payment_reference?: string | null; status: string; paid_at?: string | null; refunded_amount?: string | number; receiver?: { id: number; name: string } | null };
export type AdminOrderItem = { id: number; product_id: number; variant_id?: number | null; quantity: number; unit_price: string | number; price_mode?: "retail" | "wholesale"; line_grand_total?: string | number; refunded_quantity?: number; exchanged_quantity?: number; product: AdminProduct; variant?: { id: number; sku?: string | null } | null };
export type AdminOrder = { id: number; order_number: string; order_id?: string; source_channel: string; price_mode?: "retail" | "wholesale"; source_reference?: string | null; status: string; payment_status: string; payment_method?: string; checkout_name?: string | null; checkout_mobile_number?: string | null; checkout_email?: string | null; checkout_full_address?: string | null; checkout_district?: string | null; grand_total: string | number; paid_amount?: string | number; due_amount?: string | number; shipping_total?: string | number; discount_total?: string | number; order_date?: string | null; created_at?: string; priority?: string; delivery_status?: string | null; shop?: AdminStore | null; creator?: { id: number; name: string } | null; assignee?: { id: number; name: string } | null; items: AdminOrderItem[]; payments?: AdminPayment[]; return_requests?: AdminReturn[] };
export type AdminPromotion = { id: number; code: string; title?: string | null; description?: string | null; type: "fixed" | "percent" | "free_shipping"; value: string | number; visibility: "public" | "private"; promotion_type: "coupon" | "public_sale" | "private_coupon"; discount_scope?: string; is_active?: boolean; auto_apply?: boolean; stackable?: boolean; starts_at?: string | null; expires_at?: string | null; used_count?: number; usage_limit?: number | null; min_order_amount?: string | number | null };
export type AdminReturn = { id: number; rr_number: string; type: "return" | "exchange"; status: string; reason?: string | null; refund_total?: string | number; exchange_due_total?: string | number; restock_strategy?: string | null; resolution_type?: string | null; refund_method?: string | null; created_at?: string; order?: AdminOrder | null; items?: Array<{ id: number; quantity: number; refundable_amount?: string | number; order_item?: AdminOrderItem }> };
export type ActivityLog = { id: number; module: string; action: string; description: string; created_at: string; user?: { id: number; name: string } | null; shop?: AdminStore | null; before?: Record<string, unknown> | null; after?: Record<string, unknown> | null };
export type AdminDashboard = { metrics: Record<string, number>; daily_sales: Array<{ date: string; label: string; orders: number; sales: number }>; source_mix: Array<{ source: string; orders: number; sales: string | number }>; low_stock: InventoryRow[]; recent_orders: AdminOrder[]; generated_at: string };

export type AdminTransaction = { id: number; transaction_number: string; type: "expense" | "income"; category?: string | null; amount: string | number; payment_method: string; reason: string; reference?: string | null; attachment_url?: string | null; occurred_at: string; status: string; meta?: Record<string, unknown> | null; shop?: AdminStore | null; creator?: { id: number; name: string } | null; approver?: { id: number; name: string } | null };

export type RiskSignal = { rule: string; name: string; weight: number; facts?: Record<string, string | number | boolean | null> };
export type RiskRule = { id: number; key: string; name: string; domain: string; weight: number; is_active: boolean; config?: Record<string, string | number> | null; description?: string | null };
export type RiskEvent = { id: number; event_type: string; score: number; severity: string; decision: string; signals?: RiskSignal[] | null; context?: Record<string, unknown> | null; evaluated_at?: string };
export type FraudCase = { id: number; case_number: string; case_type: string; risk_score: number; severity: string; status: string; resolution?: string | null; resolution_note?: string | null; loss_amount?: string | number; prevented_loss?: string | number; opened_at?: string; resolved_at?: string | null; shop?: AdminStore | null; assignee?: { id: number; name: string } | null; resolver?: { id: number; name: string } | null; risk_event?: RiskEvent | null; subject?: AdminOrder | null; notes?: Array<{ id: number; note: string; created_at: string; user?: { id: number; name: string } | null }> };
export type RiskDashboard = { metrics: { open_cases: number; critical_cases: number; high_cases: number; events_24h: number; review_events_24h: number; prevented_loss: number }; score_bands: Record<"low" | "medium" | "high" | "critical", number>; recent_cases: FraudCase[]; rules: RiskRule[] };


export type AdminLegalEntity = { id: number; code: string; name: string; functional_currency: string; is_default: boolean; is_active: boolean };
export type AdminAccount = { id: number; legal_entity_id: number; code: string; name: string; type: string; normal_balance: string; report_category?: string | null; is_control: boolean; is_postable: boolean };
export type AdminFiscalPeriod = { id: number; legal_entity_id: number; code: string; name: string; starts_at: string; ends_at: string; status: string };
export type AdminPostingRule = { id: number; event_type: string; version: number; description?: string | null; is_active: boolean };
export type AdminJournalLine = { id: number; line_no: number; description?: string | null; debit: string | number; credit: string | number; currency: string; dimensions?: Record<string, unknown> | null; account: Pick<AdminAccount, "id" | "code" | "name" | "type"> };
export type AdminJournalEntry = { id: number; posting_date: string; document_date?: string | null; source_type: string; source_id: number; posting_rule_version?: number | null; status: string; description?: string | null; idempotency_key?: string | null; reversal_of_id?: number | null; posted_at?: string; legal_entity?: AdminLegalEntity; fiscal_period?: AdminFiscalPeriod; lines: AdminJournalLine[] };
export type AdminTrialBalanceRow = { account_id: number; code: string; name: string; type: string; normal_balance: string; debit: string | number; credit: string | number; net_debit: string | number };
export type AdminTrialBalance = { rows: AdminTrialBalanceRow[]; totals: { debit: number; credit: number; balanced: boolean } };
export type AdminAccountingSetup = { legal_entities: AdminLegalEntity[]; accounts: AdminAccount[]; fiscal_periods: AdminFiscalPeriod[]; posting_rules: AdminPostingRule[] };
