import type { Category, HomepageSection, Product } from "./types";

export const demoCategories: Category[] = [
  { id: 1, name: "Ihram & Packages", slug: "ihram-packages", description: "Comfort-first sets for men, women and children.", image: "/images/products/ihram-package.svg" },
  { id: 2, name: "Travel Essentials", slug: "travel-essentials", description: "Small details that make every transfer easier.", image: "/images/products/travel-kit.svg" },
  { id: 3, name: "Footwear", slug: "footwear", description: "Light, practical footwear chosen for long sacred days.", image: "/images/products/sandal.svg" },
  { id: 4, name: "Bags & Organisers", slug: "bags-organisers", description: "Keep passports, documents and valuables close.", image: "/images/products/neck-bag.svg" },
  { id: 5, name: "Prayer Essentials", slug: "prayer-essentials", description: "Thoughtful prayer and gifting pieces.", image: "/images/products/prayer-mat.svg" },
  { id: 6, name: "Sun & Weather", slug: "sun-weather", description: "Protection made for the climate of the journey.", image: "/images/products/umbrella.svg" },
];

export const demoProducts: Product[] = [
  {
    id: 101,
    name: "Premium Umrah Essential Package",
    slug: "premium-umrah-essential-package",
    selling_price: 6800,
    regular_price: 7000,
    short_description: "A considered summer-friendly package for a calm, prepared journey.",
    description: "An all-in-one package designed around comfort, simplicity and dependable essentials for Umrah.",
    image_src: ["/images/products/ihram-package.svg"],
    categories: [demoCategories[0]],
    is_featured: true,
    average_rating: 4.9,
    review_count: 28,
    available_stock: 14,
  },
  {
    id: 102,
    name: "Al Safa Royal Towel Ihram",
    slug: "al-safa-royal-towel-ihram",
    selling_price: 1800,
    regular_price: 2000,
    short_description: "Breathable cotton texture with a soft hand-feel.",
    image_src: ["/images/products/ihram-cloth.svg"],
    categories: [demoCategories[0]],
    is_featured: true,
    average_rating: 4.8,
    review_count: 41,
    available_stock: 22,
  },
  {
    id: 103,
    name: "Lightweight Ihram Sandal",
    slug: "lightweight-ihram-sandal",
    selling_price: 1200,
    regular_price: 1300,
    short_description: "Soft, grippy and easy to carry between every step.",
    image_src: ["/images/products/sandal.svg"],
    categories: [demoCategories[2]],
    average_rating: 4.7,
    review_count: 19,
    available_stock: 11,
    product_variants: [
      { id: 201, sku: "SANDAL-40", price: 1200, attributes_json: { Size: "40" }, in_stock: true },
      { id: 202, sku: "SANDAL-41", price: 1200, attributes_json: { Size: "41" }, in_stock: true },
      { id: 203, sku: "SANDAL-42", price: 1200, attributes_json: { Size: "42" }, in_stock: true },
    ],
  },
  {
    id: 104,
    name: "Anti-Theft Hajj Neck Bag",
    slug: "anti-theft-hajj-neck-bag",
    selling_price: 350,
    regular_price: 500,
    short_description: "A discreet cross-body companion for documents and currency.",
    image_src: ["/images/products/neck-bag.svg"],
    categories: [demoCategories[3]],
    average_rating: 4.8,
    review_count: 33,
    available_stock: 30,
  },
  {
    id: 105,
    name: "Travel Care Kit",
    slug: "travel-care-kit",
    selling_price: 800,
    regular_price: 890,
    short_description: "Compact care essentials for hand luggage and hotel stays.",
    image_src: ["/images/products/travel-kit.svg"],
    categories: [demoCategories[1]],
    average_rating: 4.6,
    review_count: 17,
    available_stock: 18,
  },
  {
    id: 106,
    name: "UV50+ Head Umbrella",
    slug: "uv50-head-umbrella",
    selling_price: 370,
    regular_price: 400,
    short_description: "Hands-free shade with a foldable, travel-ready profile.",
    image_src: ["/images/products/umbrella.svg"],
    categories: [demoCategories[5]],
    average_rating: 4.5,
    review_count: 12,
    available_stock: 15,
  },
  {
    id: 107,
    name: "Pocket Prayer Mat",
    slug: "pocket-prayer-mat",
    selling_price: 550,
    regular_price: 650,
    short_description: "A refined, compact prayer mat for travel and gifting.",
    image_src: ["/images/products/prayer-mat.svg"],
    categories: [demoCategories[4]],
    average_rating: 4.9,
    review_count: 23,
    available_stock: 20,
  },
  {
    id: 108,
    name: "Foldable Travel Bottle",
    slug: "foldable-travel-bottle",
    selling_price: 550,
    regular_price: 750,
    short_description: "Space-saving hydration for long days and crowded routes.",
    image_src: ["/images/products/bottle.svg"],
    categories: [demoCategories[1]],
    average_rating: 4.4,
    review_count: 9,
    available_stock: 8,
  },
];

export const demoHomepageSections: HomepageSection[] = [
  {
    id: 1,
    kind: "hero",
    eyebrow: "Prepared with intention",
    title: "Everything for the journey of a lifetime.",
    description: "Thoughtfully selected Hajj and Umrah essentials, delivered across Bangladesh with care.",
    cta_label: "Explore essentials",
    cta_url: "/shop",
    image_url: "/images/decor/madina-watercolor.jpg",
    theme: "forest",
  },
  {
    id: 2,
    kind: "category_banner",
    eyebrow: "Complete preparation",
    title: "Umrah packages, made beautifully simple.",
    description: "Start with a complete set, then personalise the details around your own journey.",
    cta_label: "Shop packages",
    cta_url: "/category/ihram-packages",
    image_url: "/images/products/ihram-package.svg",
    theme: "sand",
  },
  {
    id: 3,
    kind: "editorial_banner",
    eyebrow: "HajjMart journal",
    title: "Pack lighter. Travel calmer. Worship with focus.",
    description: "Practical guidance shaped for Bangladeshi pilgrims—from preparation to the final return home.",
    cta_label: "Read the guide",
    cta_url: "/faq",
    image_url: "/images/decor/mosque-collage.jpg",
    theme: "night",
  },
];
