import type { Category, HomepageSection, Product } from "./types";

export const demoCategories: Category[] = [
  { id: 1, name: "Ihram & Packages", name_bn: "ইহরাম ও প্যাকেজ", slug: "ihram-packages", description: "Comfort-first sets for men, women and children.", description_bn: "পুরুষ, নারী ও শিশুদের জন্য আরামদায়ক প্রস্তুত সেট।", image: "/images/products/ihram-package.svg" },
  { id: 2, name: "Travel Essentials", name_bn: "ভ্রমণের প্রয়োজনীয় সামগ্রী", slug: "travel-essentials", description: "Small details that make every transfer easier.", description_bn: "প্রতিটি যাত্রাপথ সহজ করতে ছোট কিন্তু দরকারি জিনিস।", image: "/images/products/travel-kit.svg" },
  { id: 3, name: "Footwear", name_bn: "জুতা ও স্যান্ডেল", slug: "footwear", description: "Light, practical footwear chosen for long sacred days.", description_bn: "দীর্ঘ ইবাদতের দিনের জন্য হালকা ও ব্যবহারিক পাদুকা।", image: "/images/products/sandal.svg" },
  { id: 4, name: "Bags & Organisers", name_bn: "ব্যাগ ও অর্গানাইজার", slug: "bags-organisers", description: "Keep passports, documents and valuables close.", description_bn: "পাসপোর্ট, কাগজপত্র ও মূল্যবান জিনিস হাতের কাছে রাখুন।", image: "/images/products/neck-bag.svg" },
  { id: 5, name: "Prayer Essentials", name_bn: "নামাজের প্রয়োজনীয় সামগ্রী", slug: "prayer-essentials", description: "Thoughtful prayer and gifting pieces.", description_bn: "নামাজ ও উপহারের জন্য যত্ন করে বাছাই করা সামগ্রী।", image: "/images/products/prayer-mat.svg" },
  { id: 6, name: "Sun & Weather", name_bn: "রোদ ও আবহাওয়া", slug: "sun-weather", description: "Protection made for the climate of the journey.", description_bn: "যাত্রাপথের আবহাওয়ার জন্য প্রয়োজনীয় সুরক্ষা।", image: "/images/products/umbrella.svg" },
];

export const demoProducts: Product[] = [
  {
    id: 101,
    name: "Premium Umrah Essential Package",
    name_bn: "প্রিমিয়াম উমরাহ এসেনশিয়াল প্যাকেজ",
    slug: "premium-umrah-essential-package",
    selling_price: 6800,
    regular_price: 7000,
    short_description: "A considered summer-friendly package for a calm, prepared journey.",
    short_description_bn: "স্বস্তিদায়ক ও গোছানো যাত্রার জন্য গরমের উপযোগী প্রয়োজনীয় সামগ্রীর প্যাকেজ।",
    story_intro: "A once-in-a-lifetime journey is easier when the basics are already gathered. This package gives a pilgrim a calm starting point, so the final days before departure can stay focused on preparation rather than last-minute shopping.",
    story_intro_bn: "জীবনের বিশেষ এই যাত্রা সহজ হয় যখন প্রয়োজনীয় জিনিস আগে থেকেই গুছানো থাকে। এই প্যাকেজটি যাত্রীকে শান্তভাবে প্রস্তুতি শুরু করতে সাহায্য করে, যাতে রওনা হওয়ার আগের দিনগুলো শেষ মুহূর্তের কেনাকাটার বদলে মূল প্রস্তুতিতে দেওয়া যায়।",
    description: "An all-in-one package designed around comfort, simplicity and dependable essentials for Umrah.",
    description_bn: "উমরাহর জন্য আরাম, সরলতা ও নির্ভরযোগ্য প্রয়োজনীয় সামগ্রীকে কেন্দ্র করে তৈরি একটি পূর্ণাঙ্গ প্যাকেজ।",
    image_src: ["/images/products/ihram-package.svg"],
    categories: [demoCategories[0]],
    product_kind: "package",
    package_type: "umrah",
    audience: "men",
    item_count: 12,
    package_weight: "~1 kg",
    package_disclaimer: "Items may be substituted with equal-value alternatives if unavailable.",
    package_disclaimer_bn: "কোনো পণ্য স্টকে না থাকলে সমমূল্যের বিকল্প পণ্য দেওয়া হতে পারে।",
    package_contents: [
      { name: "Ihram (2-piece set: towel + fabric)", name_bn: "ইহরাম (২-পিস সেট: তোয়ালে + কাপড়)", product_id: 102, product_slug: "al-safa-royal-towel-ihram" },
      { name: "Ihram belt", name_bn: "ইহরাম বেল্ট" },
      { name: "Shoe bag / luggage bag", name_bn: "শু ব্যাগ / লাগেজ ব্যাগ" },
      { name: "Miswak", name_bn: "মিসওয়াক" },
      { name: "Tayammum sand", name_bn: "তায়াম্মুমের মাটি" },
      { name: "Tasbih", name_bn: "তাসবিহ" },
      { name: "Fragrance-free soap & Vaseline", name_bn: "সুগন্ধিবিহীন সাবান ও ভ্যাসলিন" },
      { name: "Travel prayer mat", name_bn: "ট্রাভেল জায়নামাজ", product_id: 107, product_slug: "pocket-prayer-mat" },
      { name: "Umrah guide book + dua booklet", name_bn: "উমরাহ গাইড বই + দোয়া বই" },
      { name: "Water spray bottle", name_bn: "ওয়াটার স্প্রে বোতল" },
      { name: "Luggage stickers", name_bn: "লাগেজ স্টিকার", quantity: 2 },
    ],
    is_featured: true,
    average_rating: 4.9,
    review_count: 28,
    available_stock: 14,
  },
  {
    id: 102,
    name: "Al Safa Royal Towel Ihram",
    name_bn: "আল সাফা রয়্যাল টাওয়েল ইহরাম",
    slug: "al-safa-royal-towel-ihram",
    selling_price: 1800,
    regular_price: 2000,
    short_description: "Breathable cotton texture with a soft hand-feel.",
    short_description_bn: "নরম অনুভূতি ও বাতাস চলাচলযোগ্য কটন টেক্সচার।",
    image_src: ["/images/products/ihram-cloth.svg"],
    categories: [demoCategories[0]],
    product_kind: "single",
    audience: "men",
    is_featured: true,
    average_rating: 4.8,
    review_count: 41,
    available_stock: 22,
  },
  {
    id: 103,
    name: "Lightweight Ihram Sandal",
    name_bn: "হালকা ইহরাম স্যান্ডেল",
    slug: "lightweight-ihram-sandal",
    selling_price: 1200,
    regular_price: 1300,
    short_description: "Soft, grippy and easy to carry between every step.",
    short_description_bn: "নরম, ভালো গ্রিপযুক্ত এবং সহজে বহনযোগ্য স্যান্ডেল।",
    image_src: ["/images/products/sandal.svg"],
    categories: [demoCategories[2]],
    average_rating: 4.7,
    review_count: 19,
    available_stock: 11,
    product_variants: [
      { id: 201, sku: "SANDAL-40", price: 1200, attributes_json: { Size: "40" }, in_stock: true },
      { id: 202, sku: "SANDAL-41", price: 1200, attributes_json: { Size: "41" }, in_stock: true },
      { id: 203, sku: "SANDAL-42", price: 1200, attributes_json: { Size: "42" }, in_stock: true },
    ],
  },
  {
    id: 104,
    name: "Anti-Theft Hajj Neck Bag",
    name_bn: "অ্যান্টি-থেফট হজ নেক ব্যাগ",
    slug: "anti-theft-hajj-neck-bag",
    selling_price: 350,
    regular_price: 500,
    short_description: "A discreet cross-body companion for documents and currency.",
    short_description_bn: "কাগজপত্র ও টাকা নিরাপদে রাখার জন্য ব্যবহারিক ক্রস-বডি ব্যাগ।",
    image_src: ["/images/products/neck-bag.svg"],
    categories: [demoCategories[3]],
    average_rating: 4.8,
    review_count: 33,
    available_stock: 30,
  },
  {
    id: 105,
    name: "Travel Care Kit",
    name_bn: "ট্রাভেল কেয়ার কিট",
    slug: "travel-care-kit",
    selling_price: 800,
    regular_price: 890,
    short_description: "Compact care essentials for hand luggage and hotel stays.",
    short_description_bn: "হ্যান্ড লাগেজ ও হোটেল থাকার জন্য ছোট আকারের প্রয়োজনীয় কেয়ার সামগ্রী।",
    image_src: ["/images/products/travel-kit.svg"],
    categories: [demoCategories[1]],
    average_rating: 4.6,
    review_count: 17,
    available_stock: 18,
  },
  {
    id: 106,
    name: "UV50+ Head Umbrella",
    name_bn: "UV50+ মাথার ছাতা",
    slug: "uv50-head-umbrella",
    selling_price: 370,
    regular_price: 400,
    short_description: "Hands-free shade with a foldable, travel-ready profile.",
    short_description_bn: "হাত খালি রেখে ব্যবহার করা যায় এমন ভাঁজযোগ্য ও ভ্রমণবান্ধব ছাতা।",
    image_src: ["/images/products/umbrella.svg"],
    categories: [demoCategories[5]],
    average_rating: 4.5,
    review_count: 12,
    available_stock: 15,
  },
  {
    id: 107,
    name: "Pocket Prayer Mat",
    name_bn: "পকেট জায়নামাজ",
    slug: "pocket-prayer-mat",
    selling_price: 550,
    regular_price: 650,
    short_description: "A refined, compact prayer mat for travel and gifting.",
    short_description_bn: "ভ্রমণ ও উপহারের জন্য পরিপাটি, ছোট আকারের জায়নামাজ।",
    image_src: ["/images/products/prayer-mat.svg"],
    categories: [demoCategories[4]],
    average_rating: 4.9,
    review_count: 23,
    available_stock: 20,
  },
  {
    id: 108,
    name: "Foldable Travel Bottle",
    name_bn: "ভাঁজ করা যায় এমন ট্রাভেল বোতল",
    slug: "foldable-travel-bottle",
    selling_price: 550,
    regular_price: 750,
    short_description: "Space-saving hydration for long days and crowded routes.",
    short_description_bn: "দীর্ঘ দিন ও ভিড়ের পথে কম জায়গা নেওয়া পানির বোতল।",
    image_src: ["/images/products/bottle.svg"],
    categories: [demoCategories[1]],
    average_rating: 4.4,
    review_count: 9,
    available_stock: 8,
  },
];

export const demoHomepageSections: HomepageSection[] = [
  {
    id: 1,
    kind: "hero",
    eyebrow: "Prepared with intention",
    eyebrow_bn: "মনোযোগ দিয়ে প্রস্তুতি",
    title: "Everything for the journey of a lifetime.",
    title_bn: "জীবনের স্মরণীয় যাত্রার সব প্রয়োজনীয় জিনিস এক জায়গায়।",
    description: "Thoughtfully selected Hajj and Umrah essentials, delivered across Bangladesh with care.",
    description_bn: "যত্ন করে বাছাই করা হজ ও উমরাহর প্রয়োজনীয় সামগ্রী, সারা বাংলাদেশে ডেলিভারি।",
    cta_label: "Explore essentials",
    cta_label_bn: "প্রয়োজনীয় পণ্য দেখুন",
    cta_url: "/shop",
    image_url: "/images/decor/madina-watercolor.jpg",
    theme: "forest",
  },
  {
    id: 2,
    kind: "category_banner",
    eyebrow: "Complete preparation",
    eyebrow_bn: "সম্পূর্ণ প্রস্তুতি",
    title: "Umrah packages, made beautifully simple.",
    title_bn: "উমরাহ প্যাকেজে প্রস্তুতি হোক আরও সহজ।",
    description: "Start with a complete set, then personalise the details around your own journey.",
    description_bn: "একটি পূর্ণাঙ্গ সেট দিয়ে শুরু করুন, তারপর নিজের যাত্রা অনুযায়ী প্রয়োজনীয় জিনিস বেছে নিন।",
    cta_label: "Shop packages",
    cta_label_bn: "প্যাকেজ দেখুন",
    cta_url: "/category/ihram-packages",
    image_url: "/images/products/ihram-package.svg",
    theme: "sand",
  },
  {
    id: 3,
    kind: "editorial_banner",
    eyebrow: "HajjMart journal",
    eyebrow_bn: "HajjMart জার্নাল",
    title: "Pack lighter. Travel calmer. Worship with focus.",
    title_bn: "কম গুছান, শান্তিতে ভ্রমণ করুন, মনোযোগ দিয়ে ইবাদত করুন।",
    description: "Practical guidance shaped for Bangladeshi pilgrims—from preparation to the final return home.",
    description_bn: "প্রস্তুতি থেকে দেশে ফেরা পর্যন্ত বাংলাদেশি হাজিদের জন্য ব্যবহারিক নির্দেশনা।",
    cta_label: "Read the guide",
    cta_label_bn: "গাইড পড়ুন",
    cta_url: "/faq",
    image_url: "/images/decor/mosque-collage.jpg",
    theme: "night",
  },
];
